import {LESSONS,calculateScenario} from './registry.js';

// Presentation metadata shares stable keys and validation bounds with the calculator.
// [English label, German label, unit EN, unit DE, group, help EN, help DE]
const content={
 concert:{
 ticketPrice:['Ticket price per person','Ticketpreis pro Person','CU / person','GE / Person','primary','How much one guest pays to enter.','So viel zahlt ein Gast für den Eintritt.'],
 capacity:['How many people the venue can hold','Wie viele Personen in den Saal passen','people','Personen','primary','Empty places earn no ticket money. More space does not create buyers.','Leere Plätze bringen keine Einnahmen. Mehr Platz schafft keine Nachfrage.'],
 demand:['People willing to buy at 20 CU','Kaufbereite Personen bei 20 GE','people','Personen','audience','20 CU is the fixed reference price, not your current ticket price.','20 GE ist der feste Bezugspreis, nicht dein aktueller Ticketpreis.'],
 elasticity:['How strongly price affects demand','Wie stark der Preis die Nachfrage beeinflusst','parameter','Parameter','audience','Teaching assumptions: Low 0.5 · Medium 1 · High 2. At 0, price has no effect.','Lernannahmen: niedrig 0,5 · mittel 1 · hoch 2. Bei 0 hat der Preis keinen Einfluss.'],
 productionBudget:['Stage, DJ and production costs','Kosten für Bühne, DJ und Technik','CU total','GE gesamt','costs','Fixed cost for performers, stage and sound; excludes venue hire and guest services.','Fixkosten für Künstler, Bühne und Ton; ohne Saalmiete und Leistungen pro Gast.'],
 venueRate:['Venue hire per place of capacity','Saalmiete je verfügbarem Platz','CU / place','GE / Platz','costs','Charged for every available place, even if it stays empty.','Wird für jeden verfügbaren Platz berechnet, auch wenn er leer bleibt.'],
 perGuest:['Extra cost for each guest attending','Zusatzkosten pro anwesendem Gast','CU / guest','GE / Gast','costs','Illustrative guest supplies and services; only charged for attendees.','Beispielhafte Materialien und Leistungen; nur für anwesende Gäste.']},
 conference:{
 expectedAttendees:['People expected to attend','Erwartete Teilnehmende','people','Personen','primary','Your assumption. Changing ticket price does not change demand in this lesson.','Deine Annahme. Der Ticketpreis verändert hier die Nachfrage nicht.'],
 ticketPrice:['Ticket price per person','Ticketpreis pro Person','CU / person','GE / Person','primary','Each attendee pays this amount; sponsor money is added separately.','Jede Person zahlt diesen Betrag; Sponsoring kommt separat hinzu.'],
 workshopSeats:['People who can join a workshop at once','Gleichzeitig verfügbare Workshopplätze','places','Plätze','primary','Available places, not a claim that everyone wants to join.','Verfügbare Plätze; nicht alle möchten zwingend teilnehmen.'],
 capacity:['Maximum people the venue can hold','Maximale Personenzahl im Veranstaltungsort','people','Personen','funding','Attendance cannot exceed this number. Venue hire remains a separate fixed cost.','Die Teilnehmerzahl ist hier begrenzt. Die Saalmiete bleibt ein separater Fixbetrag.'],
 sponsor:['Money provided by sponsors','Geld von Sponsoren','CU total','GE gesamt','funding','Added to ticket income. This does not measure the sponsor’s return.','Kommt zu den Ticketeinnahmen hinzu. Misst nicht den Nutzen für Sponsoren.'],
 availableBudget:['Planned spending limit','Geplante Ausgabengrenze','CU total','GE gesamt','funding','The amount set aside for costs. It does not add to income.','Der für Kosten vorgesehene Betrag. Er erhöht nicht die Einnahmen.'],
 networkingSeats:['Seats in the networking area','Sitzplätze im Begegnungsbereich','seats','Sitzplätze','spaces','Seating available at once; not a measure of networking quality.','Gleichzeitig verfügbare Sitzplätze; kein Maß für die Qualität der Kontakte.'],
 catering:['Food and drink budget per attendee','Essen und Getränke pro Person','CU / person','GE / Person','spaces','Charged for each attendee.','Wird pro teilnehmender Person berechnet.'],
 speakerBudget:['Total speaker costs','Gesamte Vortragskosten','CU total','GE gesamt','costs','Total allowance for speakers.','Gesamtes Budget für Vortragende.'],
 venueCost:['Total venue hire cost','Gesamte Saalmiete','CU total','GE gesamt','costs','A fixed amount; changing venue capacity does not change it automatically.','Ein Fixbetrag; mehr Kapazität ändert ihn nicht automatisch.'],
 workshopRate:['Setup cost per workshop place','Einrichtungskosten je Workshopplatz','CU / place','GE / Platz','costs','Illustrative equipment and materials allowance, not just a chair.','Beispielbudget für Ausstattung und Material, nicht nur einen Stuhl.'],
 networkingRate:['Setup cost per networking seat','Einrichtungskosten je Begegnungsplatz','CU / seat','GE / Sitzplatz','costs','Furniture and setup allowance per available seat.','Budget für Möbel und Einrichtung pro verfügbarem Platz.'],
 otherFixed:['Other event costs','Weitere Veranstaltungskosten','CU total','GE gesamt','costs','Example allowance for administration and signage; excludes the categories above.','Beispielbudget für Verwaltung und Beschilderung; ohne die obigen Kategorien.']},
 factory:{
 target:['Cars we aim to build each day','Autos, die wir täglich bauen möchten','cars / day','Autos / Tag','primary','The goal; available parts may prevent us reaching it.','Das Ziel; fehlende Teile können es verhindern.'],
 openingInventory:['Parts available before day 1','Verfügbare Teile vor Tag 1','parts','Teile','primary','Each car needs one of these parts. Other components are outside this model.','Jedes Auto benötigt eines dieser Teile. Andere Komponenten werden nicht modelliert.'],
 supplierDelay:['Days before the next delivery','Tage bis zur nächsten Lieferung','days','Tage','primary','A delay of 3 means arrival before production on day 4.','3 Tage Wartezeit bedeuten Ankunft vor der Produktion an Tag 4.'],
 deliveryQuantity:['Parts in the next delivery','Teile in der nächsten Lieferung','parts','Teile','delivery','How many parts the main supplier will bring.','So viele Teile bringt der Hauptlieferant.'],
 alternativeQuantity:['Parts ordered from a backup supplier','Bestellte Teile beim Ersatzlieferanten','parts','Teile','backup','Zero means no backup order.','Null bedeutet: keine Ersatzbestellung.'],
 alternativeDay:['Day the backup parts arrive','Ankunftstag der Ersatzteile','day','Tag','backup','Received before that day’s production.','Ankunft vor der Produktion dieses Tages.'],
 alternativePremium:['Extra price per backup part','Aufpreis je Ersatzteil','CU / part','GE / Teil','backup','Added to the standard part price.','Kommt zum Standardpreis hinzu.'],
 sellingPrice:['Selling price of one finished car','Verkaufspreis eines fertigen Autos','CU / car','GE / Auto','costs','Only sold cars create sales income.','Nur verkaufte Autos bringen Einnahmen.'],
 nonComponentCost:['Other production cost per car','Weitere Produktionskosten je Auto','CU / car','GE / Auto','costs','Excludes the modeled component.','Ohne das hier modellierte Bauteil.'],
 componentCost:['Price of one standard part','Preis eines Standardteils','CU / part','GE / Teil','costs','Stock purchases and costs of parts used are recorded separately.','Bestandskäufe und Kosten verbrauchter Teile werden getrennt erfasst.'],
 carryingCost:['Daily storage cost per unused part','Tägliche Lagerkosten je ungenutztem Teil','CU / part / day','GE / Teil / Tag','costs','Charged on stock left at the end of each day.','Wird auf den Bestand am Tagesende berechnet.'],
 operatingCost:['Cost to keep the factory open each day','Tägliche Betriebskosten der Fabrik','CU / day','GE / Tag','costs','Still charged on a day when production stops.','Fallen auch an einem Tag ohne Produktion an.'],
 dailySales:['Cars customers buy each day','Autos, die Kunden täglich kaufen','cars / day','Autos / Tag','sales','Used only when automatic sale is off. Unsold cars remain in stock.','Gilt nur ohne automatischen Verkauf. Unverkaufte Autos bleiben im Lager.']}
};
export function fieldContent(id,key,lang='en'){
 const l=LESSONS[id],row=l.fields.find(r=>r[0]===key),v=content[l.scene][key],de=lang==='de';
 return {key,label:v[de?1:0],unit:v[de?3:2],group:v[4],help:v[de?6:5],min:row[3],max:row[4],step:row[5]};
}
export function setupText(id,s,lang){
 const de=lang==='de',f=n=>new Intl.NumberFormat(de?'de-DE':'en-US').format(n);
 if(id==='concert-economics')return de?'Du planst ein Konzert. Tickets bringen Geld ein; Saal, Bühne und Gäste verursachen Kosten. Ändere den Preis und beobachte Gästezahl und Gewinn.':'You are planning a live music event. Tickets bring money in; the venue, production and guests create costs. Try a different price and see how attendance and profit change.';
 if(id==='conference-economics')return de?`Du erwartest ${f(s.expectedAttendees)} Personen bei einer Konferenz. Sie brauchen Platz zum Lernen, Kennenlernen und Essen. Füge Workshopplätze hinzu und beobachte Zugang und Budget.`:`You expect ${f(s.expectedAttendees)} people at a conference. They need room to learn, meet and eat. Try adding workshop places and see how access and the budget change.`;
 return de?`Diese Fabrik möchte täglich ${f(s.target)} Autos bauen. Jedes braucht eines dieser kleinen Teile. Du startest mit ${f(s.openingInventory)} Teilen; die nächste Lieferung kommt an Tag ${s.supplierDelay+1}. Gehe die Tage nacheinander durch.`:`This factory aims to build ${f(s.target)} cars a day. Each needs one of these small parts. You start with ${f(s.openingInventory)} parts; the next delivery arrives on day ${s.supplierDelay+1}. Step through the days to see what happens.`;
}
export function workedExample(id,key,s,c,lang){
 const de=lang==='de',f=n=>new Intl.NumberFormat(de?'de-DE':'en-US',{maximumFractionDigits:2}).format(n),cu=de?'GE':'CU';
 if(key==='capacity'&&id==='concert-economics')return de?`Saalmiete jetzt: ${f(c.venueCost)} GE (${f(s.venueRate)} × ${f(s.capacity)} Plätze).`:`Venue hire now: ${f(c.venueCost)} CU (${f(s.venueRate)} × ${f(s.capacity)} places).`;
 if(key==='ticketPrice')return `${f(s.ticketPrice)} × ${f(c.attendance)} = ${f(c.registrationRevenue??c.revenue)} ${cu}`;
 const examples={venueRate:`${f(s.venueRate)} × ${f(s.capacity)} = ${f(c.venueCost)} ${cu}`,perGuest:`${f(s.perGuest)} × ${f(c.attendance)} = ${f(c.variableCost)} ${cu}`,demand:de?`${f(s.demand)} Kaufbereite bei 20 GE → ${f(c.potentialDemand)} bei ${f(s.ticketPrice)} GE.`:`${f(s.demand)} buyers at 20 CU → ${f(c.potentialDemand)} at ${f(s.ticketPrice)} CU.`,workshopSeats:`${f(Math.min(s.workshopSeats,c.attendance))} / ${f(c.attendance)} · ${c.workshopAccess===null?'—':f(c.workshopAccess)+'%'}`,workshopRate:`${f(s.workshopRate)} × ${f(s.workshopSeats)} = ${f(c.workshopCost)} ${cu}`,networkingRate:`${f(s.networkingRate)} × ${f(s.networkingSeats)} = ${f(c.networkingCost)} ${cu}`,catering:`${f(s.catering)} × ${f(c.attendance)} = ${f(c.cateringCost)} ${cu}`,supplierDelay:de?`Ankunft vor der Produktion an Tag ${s.supplierDelay+1}.`:`Arrives before production on day ${s.supplierDelay+1}.`,alternativePremium:`${f(s.componentCost)} + ${f(s.alternativePremium)} = ${f(s.componentCost+s.alternativePremium)} ${cu} / ${de?'Teil':'part'}`};
 return examples[key]||'';
}

// Pure causal explanation. Serialized into n8n alongside the unchanged calculator.
export function changeExplanation(id,s,previous,language='en'){
 const de=language==='de',c=calculateScenario(id,s),f=n=>n===null?'—':new Intl.NumberFormat(de?'de-DE':'en-US',{maximumFractionDigits:2}).format(n),cu=de?'GE':'CU';
 if(!previous)return de?'Noch keine frühere Einstellung zum Vergleich. Ändere eine Entscheidung: Hier siehst du danach Ursache und Wirkung.':'There is no earlier setting to compare yet. Try a decision: its cause and effect will appear here.';
 const a=calculateScenario(id,previous),keys=Object.keys(s).filter(k=>s[k]!==previous[k]);
 if(!keys.length)return de?'Die Einstellungen sind unverändert.':'The settings are unchanged.';
 if(id==='concert-economics'){
  const price=keys.includes('ticketPrice')?(de?`Ticketpreis: ${f(previous.ticketPrice)} → ${f(s.ticketPrice)} GE. `:`Ticket price: ${f(previous.ticketPrice)} → ${f(s.ticketPrice)} CU. `):'';
  const capacity=keys.includes('capacity')?(de?`Saalgröße: ${f(previous.capacity)} → ${f(s.capacity)} Plätze. `:`Venue size: ${f(previous.capacity)} → ${f(s.capacity)} places. `):'';
  const demand=keys.includes('demand')?(de?`Auch die Nachfrageannahme wurde von ${f(previous.demand)} auf ${f(s.demand)} geändert. `:`The demand assumption also changed from ${f(previous.demand)} to ${f(s.demand)}. `):'';
  const cause=keys.length===1&&keys[0]==='capacity'?(de?`Mehr Platz erzeugt keine Käufer. Die Saalmiete ändert sich von ${f(a.venueCost)} auf ${f(c.venueCost)} GE. `:`Extra space does not create buyers. Venue hire changes from ${f(a.venueCost)} to ${f(c.venueCost)} CU. `):keys.length===1&&keys[0]==='ticketPrice'?(de?`Die Preisannahme verändert die Nachfrage; Kosten pro anwesendem Gast ändern sich von ${f(a.variableCost)} auf ${f(c.variableCost)} GE. `:`The price assumption changes demand; costs for attending guests change from ${f(a.variableCost)} to ${f(c.variableCost)} CU. `):'';
  return price+capacity+demand+(de?`Erwartete Gäste: ${f(a.attendance)} → ${f(c.attendance)}. Ticketumsatz: ${f(a.revenue)} → ${f(c.revenue)} GE${a.revenue===c.revenue?' (unverändert)':''}. `:`Expected guests: ${f(a.attendance)} → ${f(c.attendance)}. Ticket revenue: ${f(a.revenue)} → ${f(c.revenue)} CU${a.revenue===c.revenue?' (unchanged)':''}. `)+cause+(de?`Gesamtkosten: ${f(a.totalCost)} → ${f(c.totalCost)} GE. Ergebnis: ${f(a.profit)} → ${f(c.profit)} GE${c.profit<0?' (Verlust)':''}.`:`Total costs: ${f(a.totalCost)} → ${f(c.totalCost)} CU. Profit: ${f(a.profit)} → ${f(c.profit)} CU${c.profit<0?' (loss)':''}.`);
 }
 if(id==='conference-economics'){
  const workshop=keys.includes('workshopSeats')?(de?`Workshopplätze: ${f(previous.workshopSeats)} → ${f(s.workshopSeats)}. ${f(Math.min(c.attendance,s.workshopSeats)-Math.min(a.attendance,previous.workshopSeats))} zusätzliche Personen können gleichzeitig teilnehmen. Zugang: ${f(a.workshopAccess)}% → ${f(c.workshopAccess)}%. Einrichtungskosten: ${f(a.workshopCost)} → ${f(c.workshopCost)} GE. `:`Workshop places: ${f(previous.workshopSeats)} → ${f(s.workshopSeats)}. ${f(Math.min(c.attendance,s.workshopSeats)-Math.min(a.attendance,previous.workshopSeats))} more people can join at once. Access: ${f(a.workshopAccess)}% → ${f(c.workshopAccess)}%. Setup costs: ${f(a.workshopCost)} → ${f(c.workshopCost)} CU. `):'';
  return workshop+(de?`Einnahmen: ${f(a.revenue)} → ${f(c.revenue)} GE. Kosten: ${f(a.totalCost)} → ${f(c.totalCost)} GE. Verbleibendes Geld: ${f(a.profit)} → ${f(c.profit)} GE. Die Ausgabengrenze von ${f(s.availableBudget)} GE ist separat; Kosten liegen ${f(c.budgetGap)} GE darüber.`:`Income: ${f(a.revenue)} → ${f(c.revenue)} CU. Costs: ${f(a.totalCost)} → ${f(c.totalCost)} CU. Money left: ${f(a.profit)} → ${f(c.profit)} CU. Your ${f(s.availableBudget)} CU spending limit is separate; costs are ${f(c.budgetGap)} CU above it.`);
 }
 const row=c.history.at(-1),opening=row?c.inventory+c.produced-c.received:s.openingInventory;
 if(keys.length===1&&keys[0]==='elapsedDays')return de?`Tag ${c.day}: ${f(opening)} Teile zu Beginn + ${f(c.received)} gelieferte Teile, dann ${f(c.produced)} verbaute Teile = ${f(c.inventory)} Teile am Ende. Heute ${f(c.produced)} Autos gebaut; bisher ${f(c.cumulativeOutput)} von ${f(s.target*c.day)} geplanten Autos. ${c.produced<s.target?'Fehlende Teile begrenzen die Produktion.':'Genug Teile für das Tagesziel.'}`:`Day ${c.day}: ${f(opening)} starting parts + ${f(c.received)} delivered, then ${f(c.produced)} used = ${f(c.inventory)} parts left. Built ${f(c.produced)} cars today; ${f(c.cumulativeOutput)} so far against a ${f(s.target*c.day)}-car plan. ${c.produced<s.target?'Missing parts limit production.':'Enough parts to reach today’s target.'}`;
 return de?`Mit den neuen Einstellungen neu gestartet (Tag ${c.day}). Anfangsbestand: ${f(s.openingInventory)} Teile. Hauptlieferung: ${f(s.deliveryQuantity)} Teile an Tag ${s.supplierDelay+1}. ${s.alternativeQuantity?`Ersatzlieferung: ${f(s.alternativeQuantity)} Teile an Tag ${s.alternativeDay}, je ${f(s.componentCost+s.alternativePremium)} GE.`:'Keine Ersatzlieferung geplant.'}`:`Restarted with the new settings (day ${c.day}). Starting stock: ${f(s.openingInventory)} parts. Main delivery: ${f(s.deliveryQuantity)} parts on day ${s.supplierDelay+1}. ${s.alternativeQuantity?`Backup delivery: ${f(s.alternativeQuantity)} parts on day ${s.alternativeDay}, at ${f(s.componentCost+s.alternativePremium)} CU each.`:'No backup delivery is scheduled.'}`;
}

export function deriveSceneState(id,s,c,selectedZone){
 const kind=LESSONS[id].scene;
 return {kind,selectedZone,people:c.attendance||0,occupancy:c.occupancy||0,workshopShare:(c.workshopAccess||0)/100,workshopPlaces:s.workshopSeats||0,parts:c.inventory||0,received:c.received||0,producing:kind==='factory'&&c.day>0&&c.produced>0,day:c.day||0,finished:c.finishedInventory||0,sold:c.sales||0,scale:kind==='concert'?Math.min(3,Math.log10(s.capacity/200+1)):1};
}

export function zoneContent(id,zone,s,c,lang){
 const de=lang==='de',f=n=>new Intl.NumberFormat(de?'de-DE':'en-US',{maximumFractionDigits:2}).format(n),cu=de?'GE':'CU',pick=(en,deText)=>de?deText:en;
 const map={
 entrance:[`${f(c.attendance)} × ${f(s.ticketPrice)} = ${f(c.revenue)} ${cu}.`,pick('Empty places earn no ticket money.','Leere Plätze bringen kein Ticketgeld.'),{ticketPrice:Math.min(500,s.ticketPrice+10)}],
 stage:[`${f(s.productionBudget)} ${cu}.`,pick('Stage, DJ and sound cost money even when attendance falls.','Bühne, DJ und Ton kosten auch bei weniger Gästen Geld.'),{productionBudget:Math.min(10000000,s.productionBudget+250)}],
 audience:[pick(`${f(c.attendance)} of ${f(s.capacity)} places filled. ${f(c.potentialDemand)} people would buy at this price.`,`${f(c.attendance)} von ${f(s.capacity)} Plätzen belegt. ${f(c.potentialDemand)} Personen würden zu diesem Preis kaufen.`),pick('Venue capacity limits attendance; it never creates demand.','Die Saalgröße begrenzt die Gästezahl; sie schafft keine Nachfrage.'),{capacity:Math.min(100000,Math.max(1000,s.capacity*2))}],
 registration:[pick(`Ticket income ${f(c.registrationRevenue)} + sponsors ${f(s.sponsor)} = ${f(c.revenue)} CU.`,`Tickets ${f(c.registrationRevenue)} + Sponsoren ${f(s.sponsor)} = ${f(c.revenue)} GE.`),pick('Income and your spending limit are separate.','Einnahmen und Ausgabengrenze sind verschieden.'),{ticketPrice:Math.min(1000,s.ticketPrice+10)}],
 speakers:[`${f(s.speakerBudget)} ${cu}.`,pick('This is the total speaker allowance, independent of attendance.','Das gesamte Vortragsbudget ist unabhängig von der Teilnehmerzahl.'),{speakerBudget:Math.min(10000000,s.speakerBudget+500)}],
 workshop:[pick(`${f(Math.min(s.workshopSeats,c.attendance))} of ${f(c.attendance)} people can join at once (${c.workshopAccess===null?'—':f(c.workshopAccess)+'%'}).`,`${f(Math.min(s.workshopSeats,c.attendance))} von ${f(c.attendance)} Personen können gleichzeitig teilnehmen (${c.workshopAccess===null?'—':f(c.workshopAccess)+'%'}).`),pick('Places show access, not workshop demand or learning quality.','Plätze zeigen Zugang, nicht Nachfrage oder Lernerfolg.'),{workshopSeats:Math.min(100000,s.workshopSeats+100)}],
 networking:[pick(`${f(s.networkingSeats)} seats for ${f(c.attendance)} people.`,`${f(s.networkingSeats)} Sitzplätze für ${f(c.attendance)} Personen.`),pick('More seats cost money; they do not measure the quality of connections.','Mehr Sitzplätze kosten Geld; sie messen nicht die Qualität der Kontakte.'),{networkingSeats:Math.min(100000,s.networkingSeats+50)}],
 catering:[`${f(s.catering)} × ${f(c.attendance)} = ${f(c.cateringCost)} ${cu}.`,pick('Food and drink costs grow with attendance.','Essen und Getränke kosten bei mehr Teilnehmenden mehr.'),{catering:Math.min(1000,s.catering+5)}],
 supplier:[pick(`${f(s.deliveryQuantity)} parts arrive before production on day ${s.supplierDelay+1}. ${s.alternativeQuantity?`Backup: ${f(s.alternativeQuantity)} on day ${s.alternativeDay}.`:'No backup delivery is scheduled.'}`,`${f(s.deliveryQuantity)} Teile kommen vor der Produktion an Tag ${s.supplierDelay+1}. ${s.alternativeQuantity?`Ersatz: ${f(s.alternativeQuantity)} an Tag ${s.alternativeDay}.`:'Keine Ersatzlieferung geplant.'}`),pick(`Backup parts cost ${f(s.componentCost+s.alternativePremium)} CU each. Timing matters.`,`Ersatzteile kosten je ${f(s.componentCost+s.alternativePremium)} GE. Der Zeitpunkt zählt.`),{alternativeQuantity:s.target*2,alternativeDay:2}],
 components:[pick(`${f(c.inventory)} parts left after day ${c.day}.`,`${f(c.inventory)} Teile nach Tag ${c.day} übrig.`),pick('Each car consumes one part. Unused parts incur storage costs.','Jedes Auto verbraucht ein Teil. Ungenutzte Teile verursachen Lagerkosten.'),{openingInventory:Math.min(1000000,s.openingInventory+100)}],
 assembly:[pick(`${f(c.produced)} cars built today; target ${f(s.target)}.`,`${f(c.produced)} Autos heute gebaut; Ziel ${f(s.target)}.`),pick(c.day===0?'Start day 1 to receive parts, build cars and record the result.':c.produced<s.target?'The missing part blocks this station. A stopped line still has operating costs.':'Parts are available and the line can run.',c.day===0?'Starte Tag 1: Teile empfangen, Autos bauen, Ergebnis erfassen.':c.produced<s.target?'Das fehlende Teil blockiert diese Station. Auch Stillstand verursacht Betriebskosten.':'Teile sind vorhanden; die Linie kann laufen.'),{elapsedDays:Math.min(30,c.day+1)}],
 finished:[pick(`${f(c.cumulativeOutput)} built, ${f(c.sales)} sold, ${f(c.finishedInventory)} waiting to sell — so far.`,`${f(c.cumulativeOutput)} gebaut, ${f(c.sales)} verkauft, ${f(c.finishedInventory)} unverkauft — bisher.`),pick('Building a car and selling it are separate events.','Ein Auto bauen und es verkaufen sind getrennte Vorgänge.'),{sellImmediately:false,dailySales:Math.floor(s.target/2)}]
 };
 const [status,meaning,values]=map[zone];return {status,meaning,values};
}
