import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('test-results',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1080},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.TEST_BASE_URL || 'http://localhost:3000';
await page.goto(base,{waitUntil:'networkidle'});
await page.waitForFunction(()=>document.querySelector('#venue')?.dataset.loaded==='true',null,{timeout:60000});
assert.equal(await page.locator('#profit').textContent(),'750');
await page.screenshot({path:'test-results/desktop.png',fullPage:true});
await page.locator('[data-price="30"]').click();assert.equal(await page.locator('#profit').textContent(),'1,000');
await page.locator('#question').fill('Why do costs fall when fewer people attend?');await page.locator('#ask').click();
await page.waitForFunction(()=>!document.querySelector('#ask').disabled,{timeout:30000});
assert.match(await page.locator('#explanation').textContent(),/cost/i);
console.log('Desktop tutor delivery:',await page.locator('#delivery').textContent());
await page.locator('#language').selectOption('de');
assert.equal(await page.locator('#profit').textContent(),'1.000');
await page.locator('#question').fill('Warum sinken die Kosten bei weniger Gästen?');await page.locator('#ask').click();
await page.waitForFunction(()=>!document.querySelector('#ask').disabled,{timeout:30000});
assert.match(await page.locator('#explanation').textContent(),/Kosten|Gewinn|Gäste/);
await page.locator('[data-answer="up"]').click();assert.match(await page.locator('#quiz-feedback').textContent(),/Genau/);
await page.screenshot({path:'test-results/german.png',fullPage:true});
const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
await mobile.goto(base,{waitUntil:'networkidle'});
await mobile.waitForFunction(()=>document.querySelector('#venue')?.dataset.loaded==='true',null,{timeout:60000});
assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await mobile.screenshot({path:'test-results/mobile.png',fullPage:true});
await mobile.locator('#toggle-view').click();assert.equal(await mobile.locator('#flat-view').isVisible(),true);
await mobile.locator('[data-price="30"]').click();assert.equal(await mobile.locator('#profit').textContent(),'1,000');
const failed=await browser.newPage();await failed.route('**/models/concert.glb',r=>r.abort());
await failed.goto(base,{waitUntil:'networkidle'});await failed.locator('#flat-view').waitFor({state:'visible'});
await failed.locator('[data-price="30"]').click();assert.equal(await failed.locator('#profit').textContent(),'1,000');
assert.deepEqual(errors,[]);
await page.route('**/api/lesson',route=>route.abort());
await page.locator('#question').fill('Was sind Fixkosten?');await page.locator('#ask').click();
await page.waitForFunction(()=>!document.querySelector('#ask').disabled);
assert.match(await page.locator('#delivery').textContent(),/vorbereitete/);
console.log('PASS: 3D load, 20/30 calculations, English/German tutor, quiz, 390px viewport, 2D switch, failed asset fallback. Actual phone still requires human testing.');
await browser.close();
