export const mediaPlan={
  concert:{title:'A full house. A better business?',steps:[
    {values:{ticketPrice:20,capacity:200,demand:150},zone:'entrance',en:'A full house looks like success. But does a bigger crowd always mean a better business? Let us explore a miniature concert, using invented numbers.',de:'Ein volles Haus sieht nach Erfolg aus. Aber bedeutet ein größeres Publikum immer ein besseres Geschäft? Wir erkunden ein kleines Konzert mit erfundenen Zahlen.'},
    {values:{ticketPrice:20,capacity:200,demand:150},zone:'stage',en:'At a ticket price of twenty, one hundred and fifty guests attend. Revenue is three thousand. After production, venue and per-person costs, profit is seven hundred and fifty.',de:'Bei einem Ticketpreis von zwanzig kommen hundertfünfzig Gäste. Der Umsatz beträgt dreitausend. Nach Produktionskosten, Saalkosten und Kosten je Gast bleiben siebenhundertfünfzig Gewinn.'},
    {values:{ticketPrice:30},zone:'audience',en:'Raise the ticket price to thirty. Now one hundred guests attend. Revenue stays at three thousand, but costs fall. Profit rises to one thousand.',de:'Erhöhe den Ticketpreis auf dreißig. Jetzt kommen hundert Gäste. Der Umsatz bleibt bei dreitausend, aber die Kosten sinken. Der Gewinn steigt auf tausend.'},
    {values:{ticketPrice:20,capacity:1000,demand:150},zone:'stage',en:'Now rent a thousand-place venue without changing interest. The crowd stays the same, while venue costs rise. The event loses twelve hundred and fifty.',de:'Miete nun einen Saal mit tausend Plätzen, ohne die Nachfrage zu ändern. Das Publikum bleibt gleich, aber die Saalkosten steigen. Das Event verliert eintausendzweihundertfünfzig.'},
    {values:{capacity:1000,demand:900},zone:'audience',en:'More capacity is not the same as more demand. Try your own assumptions. Follow the money, and remember: revenue is not profit.',de:'Mehr Kapazität ist nicht dasselbe wie mehr Nachfrage. Teste deine eigenen Annahmen. Verfolge das Geld und denke daran: Umsatz ist nicht Gewinn.'}
  ]},
  conference:{title:'Build a conference people love.',steps:[
    {values:{},zone:'registration',en:'What makes a conference worth attending? Money matters, but so does access. This miniature conference lets you explore the trade-off without inventing satisfaction scores.',de:'Was macht eine Konferenz lohnenswert? Geld ist wichtig, aber auch Zugang. In dieser kleinen Konferenz erkunden wir den Zielkonflikt, ohne Zufriedenheitswerte zu erfinden.'},
    {values:{},zone:'speakers',en:'Five hundred attendees pay forty each. Sponsors contribute ten thousand. Total revenue is thirty thousand. Costs are twenty-five thousand, leaving a five-thousand surplus.',de:'Fünfhundert Teilnehmende zahlen jeweils vierzig. Sponsoren tragen zehntausend bei. Der Gesamtumsatz beträgt dreißigtausend. Kosten von fünfundzwanzigtausend lassen fünftausend Überschuss.'},
    {values:{workshopSeats:200},zone:'workshop',en:'There are only two hundred workshop seats. That gives forty percent of attendees a place. A healthy surplus can still leave a queue outside the workshop.',de:'Es gibt nur zweihundert Workshopplätze. Damit bekommen vierzig Prozent einen Platz. Trotz eines guten Überschusses kann vor dem Workshop eine Schlange entstehen.'},
    {values:{workshopSeats:300},zone:'workshop',en:'Add one hundred workshop seats. Access rises to sixty percent. Costs increase by one thousand, and surplus falls to four thousand. Both changes are visible.',de:'Füge hundert Workshopplätze hinzu. Der Zugang steigt auf sechzig Prozent. Die Kosten steigen um tausend und der Überschuss fällt auf viertausend. Beide Veränderungen sind sichtbar.'},
    {values:{},zone:'networking',en:'The choice is about priorities and constraints. Compare two plans, explore catering and shared space, and remember that sponsor contributions alone do not measure sponsor return.',de:'Es geht um Prioritäten und Grenzen. Vergleiche zwei Pläne und erkunde Verpflegung und Begegnungsräume. Sponsorbeiträge allein messen nicht den Nutzen für den Sponsor.'}
  ]},
  factory:{title:'A whole car. One missing part.',steps:[
    {values:{elapsedDays:0},zone:'components',en:'How can one inexpensive component stop an expensive car? This factory needs one part for every vehicle. There are no other bottlenecks in our simplified model.',de:'Wie kann ein günstiges Bauteil ein teures Auto aufhalten? Diese Fabrik benötigt ein Teil je Fahrzeug. Andere Engpässe gibt es in unserem vereinfachten Modell nicht.'},
    {values:{elapsedDays:1},zone:'assembly',en:'The daily target is one hundred vehicles. Starting with one hundred and fifty parts, day one produces one hundred and leaves fifty in stock.',de:'Das Tagesziel beträgt hundert Fahrzeuge. Mit hundertfünfzig Bauteilen produziert Tag eins hundert Fahrzeuge. Fünfzig Teile bleiben im Lager.'},
    {values:{elapsedDays:3},zone:'assembly',en:'Day two can produce only fifty. On day three the line stops. These are unfilled production opportunities, not automatically lost sales.',de:'Tag zwei kann nur fünfzig Fahrzeuge produzieren. An Tag drei steht das Band still. Das sind nicht genutzte Produktionsmöglichkeiten, nicht automatisch verlorene Verkäufe.'},
    {values:{elapsedDays:4},zone:'supplier',en:'Two hundred parts arrive before production on day four. The line makes one hundred vehicles and keeps one hundred parts. Total output is two hundred and fifty.',de:'Zweihundert Teile kommen vor der Produktion an Tag vier an. Die Linie baut hundert Fahrzeuge und behält hundert Teile. Insgesamt wurden zweihundertfünfzig Fahrzeuge produziert.'},
    {values:{elapsedDays:4,alternativeQuantity:200,alternativeDay:2},zone:'finished',en:'A second supplier can help if parts arrive in time. Compare its premium with safety stock. Under this example, completed vehicles sell that day. Resilience has costs as well as benefits.',de:'Ein zweiter Lieferant hilft, wenn die Teile rechtzeitig kommen. Vergleiche seinen Aufpreis mit Sicherheitsbestand. Hier werden fertige Fahrzeuge am selben Tag verkauft. Widerstandsfähigkeit hat Kosten und Vorteile.'}
  ]}
};
