import {chromium} from 'playwright';
import {mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:3177';
await mkdir('docs/evidence/after',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1080}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='warning')console.log(m.text().slice(0,250));});
await page.goto(base,{waitUntil:'networkidle'});await page.waitForFunction(()=>document.querySelector('#venue')?.dataset.loaded==='true',null,{timeout:60000});
assert.equal(await page.locator('[data-metric=profit]').textContent(),'750');
await page.locator('[data-zone=stage]').click();assert.match(await page.locator('#context-text').textContent(),/Production/);
await page.locator('#field-capacity').fill('1000');await page.locator('#field-capacity').dispatchEvent('change');assert.equal(await page.locator('[data-metric=attendance]').textContent(),'150');assert.equal(await page.locator('[data-metric=profit]').textContent(),'-1,250');
await page.locator('#field-demand').fill('900');await page.locator('#field-demand').dispatchEvent('change');assert.equal(await page.locator('[data-metric=profit]').textContent(),'10,000');
await page.locator('#save-scenario').click();await page.locator('#field-ticketPrice').fill('30');await page.locator('#field-ticketPrice').dispatchEvent('change');assert.equal(await page.locator('#comparison').isVisible(),true);
await page.locator('#reset-scenario').click();await page.screenshot({path:'docs/evidence/after/concert-desktop.png',fullPage:true});
await page.locator('[data-lesson=conference-economics]').click();await page.waitForFunction(()=>document.querySelector('#venue')?.dataset.loaded==='true');assert.equal(await page.locator('[data-metric=profit]').textContent(),'5,000');
await page.locator('#field-workshopSeats').fill('300');await page.locator('#field-workshopSeats').dispatchEvent('change');assert.equal(await page.locator('[data-metric=profit]').textContent(),'4,000');assert.equal(await page.locator('[data-metric=workshopAccess]').textContent(),'60');
await page.screenshot({path:'docs/evidence/after/conference-desktop.png',fullPage:true});
await page.locator('[data-lesson=factory-supply-chain]').click();await page.waitForFunction(()=>document.querySelector('#venue')?.dataset.loaded==='true');
for(const [produced,stock] of [[100,50],[50,0],[0,0],[100,100]]){await page.locator('#advance-day').click();assert.equal(await page.locator('[data-metric=produced]').textContent(),String(produced));assert.equal(await page.locator('[data-metric=inventory]').textContent(),String(stock));}
await page.screenshot({path:'docs/evidence/after/factory-desktop.png',fullPage:true});
await page.locator('#language').selectOption('de');assert.equal(await page.locator('#field-target').inputValue(),'100');
await page.reload({waitUntil:'networkidle'});assert.match(await page.locator('h1').textContent(),/Auto/);
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await mobile.goto(base,{waitUntil:'networkidle'});await mobile.waitForFunction(()=>document.querySelector('#venue')?.dataset.loaded==='true');assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await mobile.locator('.control-tray>summary').click();await mobile.locator('#field-ticketPrice').fill('30');await mobile.locator('#field-ticketPrice').dispatchEvent('change');assert.equal(await mobile.locator('[data-metric=profit]').textContent(),'1,000');await mobile.screenshot({path:'docs/evidence/after/concert-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('PASS: all three scenes; capacity independent from demand; compare; conference tradeoff; factory four-day case; German/direct reload; mobile control tray.');await browser.close();
