import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/700.css';
import '@fontsource/manrope/500.css';
import '@fontsource/manrope/800.css';
import './style.css';
import {LESSONS,defaults,normalizeId,validateScenario,calculateScenario} from '../shared/registry.js';
import {preparedLesson,approvedParagraphs,validateLesson} from '../shared/lesson.js';
import {parseCommand} from '../shared/commands.js';
import {voiceController} from './voice.js';
import './experience.css';

const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const url=new URL(location.href);let lang=url.searchParams.get('lang')==='de'?'de':'en';
let id=normalizeId(location.pathname.split('/')[2]||url.searchParams.get('lesson')||'concert');if(!LESSONS[id])id='concert-economics';
let scenario=defaults(id),previous=null,saved=null,revision=0,turn=0,world,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,paused=reduced,flat=false,runTimer,lastAnswer,lastRequest,selectedZone=null;
const sessionId=crypto.randomUUID();const tr=(en,de)=>lang==='de'?de:en;const f=n=>n===null?tr('N/A','n. a.'):new Intl.NumberFormat(lang==='de'?'de-DE':'en-US',{maximumFractionDigits:2}).format(n);
const lesson=()=>LESSONS[id];const snapshot=(question,inputMode='text')=>({requestId:crypto.randomUUID(),sessionId,topicId:id,language:lang,question,scenario:{...scenario},previousScenario:previous?{...previous}:null,scenarioRevision:revision,inputMode});
const voice=voiceController({language:()=>lang,onTranscript:text=>{if($('#question')){$('#question').value=text;$('#transcript').textContent=tr('You said: ','Du sagtest: ')+text;ask(text,'voice');}},onStatus:text=>{if($('#voice-status'))$('#voice-status').textContent=text;},onRecording:yes=>{if($('#mic')){$('#mic').disabled=yes;$('#record-stop').hidden=!yes;$('#record-cancel').hidden=!yes;$('#mic').classList.toggle('recording',yes);}}});

function invalidate(){turn++;revision++;lastAnswer=null;lastRequest=null;voice.cancel();if($('#ask')){$('#ask').disabled=false;$('#ask').textContent=tr('Ask question','Frage stellen');}if($('#replay'))$('#replay').disabled=true;}
function field(row){const [key,en,de,min,max,step]=row;const value=scenario[key];return `<label class="field" for="field-${key}"><span>${tr(en,de)}</span><div><input id="field-${key}" data-input="${key}" type="number" min="${min}" max="${max}" step="${step}" value="${value}" inputmode="decimal"/></div>${['ticketPrice','capacity','demand','expectedAttendees','workshopSeats','supplierDelay','openingInventory'].includes(key)?`<input aria-label="${tr(en,de)} ${tr('slider','Regler')}" data-range="${key}" type="range" min="${min}" max="${key==='capacity'||key==='demand'||key==='expectedAttendees'||key==='workshopSeats'?Math.max(2000,value):key==='ticketPrice'?Math.max(100,value):max}" step="${step}" value="${value}"/>`:''}</label>`;}
function render(push=false){
  world?.dispose();world=null;voice.cancel();clearInterval(runTimer);runTimer=null;turn++;document.documentElement.lang=lang;
  const l=lesson();if(push)history.pushState({},'',`/lessons/${id}?lang=${lang}`);
  document.title=l.title[lang]+' — The Economics of Everything';
  $('#app').innerHTML=`<header class="site-header"><a class="brand" href="/"><span class="brand-mark">e<span>•</span></span><span>The Economics<br>of Everything</span></a><span class="header-lab">${tr('SMALL WORLDS. REAL INSIGHTS.','KLEINE WELTEN. ECHTE ERKENNTNISSE.')}</span><select id="language" aria-label="Language / Sprache"><option value="en" ${lang==='en'?'selected':''}>English</option><option value="de" ${lang==='de'?'selected':''}>Deutsch</option></select></header>
  <main class="experience"><nav class="lesson-nav" aria-label="${tr('Choose a lesson','Lektion wählen')}">${Object.values(LESSONS).map((v,i)=>`<a href="/lessons/${v.id}?lang=${lang}" data-lesson="${v.id}" ${id===v.id?'aria-current="page"':''}><span>${v.icon}</span><div><small>0${i+1}</small>${v.title[lang]}</div></a>`).join('')}</nav>
  <div class="compact-title"><div><h1>${l.question[lang]}</h1><p>${l.subtitle[lang]}</p></div><button id="watch" class="primary">▶ ${tr('Watch the short story','Die Kurzgeschichte ansehen')}</button></div>
  <div class="experience-grid"><section class="world-panel"><div class="world-top"><span class="eyebrow">${tr('YOUR LIVE WORLD','DEINE LIVE-WELT')}</span><div class="world-tools"><button id="pause" aria-pressed="${paused}">${paused?tr('Play motion','Bewegung starten'):tr('Pause motion','Bewegung pausieren')}</button><button id="reset-camera">${tr('Reset view','Ansicht zurücksetzen')}</button><button id="toggle-view">${flat?'3D':'2D'}</button></div></div><div class="canvas-wrap"><canvas id="venue" aria-label="${tr('Drag to orbit. Select a labeled zone below to explore.','Ziehen zum Drehen. Wähle unten einen Bereich.') }" tabindex="0"></canvas><div id="scene-loading" role="status">${tr('Opening your world…','Deine Welt wird geöffnet…')}</div><div id="flat-view" hidden></div><div class="scene-badge" id="scene-badge"></div></div><div class="world-bottom"><span>${tr('Drag to explore · tap a zone','Ziehen zum Erkunden · Bereich antippen')}</span><span>${tr('Figures represent groups, not individual headcounts.','Figuren stehen für Gruppen, nicht Einzelpersonen.')}</span></div>
  <div class="hotspots">${l.zones.map((z,i)=>`<button data-zone="${z}" aria-pressed="false">${String(i+1).padStart(2,'0')} ${l.zoneLabels[lang][i]}</button>`).join('')}</div><div class="context-card" aria-live="polite"><div><span class="eyebrow" id="context-title">${tr('EXPLORE A PART OF THE WORLD','ERKUNDE EINEN BEREICH')}</span><p id="context-text">${tr('Select a labeled zone above. The camera will move closer and its explanation will appear here.','Wähle oben einen Bereich. Die Kamera fährt näher heran und hier erscheint die Erklärung.')}</p></div><button id="context-ask">${tr('Ask about this','Dazu eine Frage stellen')}</button></div>
  <div class="quick-results" aria-live="polite" id="quick-results"></div></section>
  <aside><details class="control-tray" ${innerWidth>760?'open':''}><summary>${tr('Adjust your scenario','Dein Szenario anpassen')} <span>＋</span></summary><div class="preset-row">${l.presets.map((p,i)=>`<button data-preset="${i}">${p[lang]}</button>`).join('')}</div><p class="control-hint">${tr('Presets change several assumptions. Capacity alone never creates demand.','Voreinstellungen ändern mehrere Annahmen. Kapazität allein erzeugt keine Nachfrage.')}</p><div class="fields">${l.fields.filter(r=>!r[7]).map(field).join('')}</div><details class="advanced"><summary>${tr('Advanced cost assumptions','Weitere Kostenannahmen')}</summary>${l.fields.filter(r=>r[7]).map(field).join('')}${l.scene==='factory'?`<label class="check"><input id="sell-immediately" type="checkbox" ${scenario.sellImmediately?'checked':''}>${tr('Sell every completed vehicle that day','Jedes fertige Fahrzeug am selben Tag verkaufen')}</label>`:''}</details></details>
  ${l.scene==='factory'?`<section class="day-controls"><span id="day-label"></span><div><button id="advance-day">${tr('Advance one day','Einen Tag weiter')}</button><button id="run-days">${tr('Run days','Tage abspielen')}</button></div><small>${tr('Receive → produce → sell → accrue costs. Maximum 30 days.','Empfangen → produzieren → verkaufen → Kosten. Höchstens 30 Tage.')}</small></section>`:''}
  <div class="scenario-actions"><button id="reset-scenario">${tr('Reset scenario','Szenario zurücksetzen')}</button><button id="save-scenario">${tr('Save A for comparison','A zum Vergleich speichern')}</button></div><p id="change-notice" role="status"></p><section class="result-card"><div class="eyebrow">${tr('THE NUMBERS','DIE ZAHLEN')}</div><div id="metrics"></div><small>${tr('Illustrative currency units. No real-world forecast.','Erfundene Geldeinheiten. Keine echte Prognose.')}</small></section></aside></div>
  <section id="comparison" class="comparison" hidden></section>
  <section class="tutor-section"><div><div class="eyebrow">${tr('ASK. LISTEN. TRY SOMETHING.','FRAGEN. ZUHÖREN. AUSPROBIEREN.')}</div><h2>${tr('Ask about this scenario.','Frage zu diesem Szenario.')}</h2><p>${tr('Type a question or speak. Your answer uses the lesson and numbers you see right now.','Tippe oder sprich. Die Antwort bezieht sich auf die aktuelle Lektion und deine Zahlen.')}</p><div class="question-chips">${l.questions[lang].map((q,i)=>`<button data-question="${i}">${q}</button>`).join('')}</div></div><div class="tutor-card"><div class="tutor-heading"><span class="tutor-avatar">e•</span><span id="delivery">${tr('Prepared explanation','Vorbereitete Erklärung')}</span></div><p id="explanation" aria-live="polite"></p><p id="transcript"></p><form id="ask-form"><label for="question">${tr('Your question','Deine Frage')}</label><textarea id="question" maxlength="600" rows="2" placeholder="${l.questions[lang][0]}" required></textarea><div class="form-bottom"><button type="button" id="mic">● ${tr('Speak a question','Frage sprechen')}</button><button type="button" id="record-stop" hidden>${tr('Stop & send','Stoppen & senden')}</button><button type="button" id="record-cancel" hidden>${tr('Cancel','Abbrechen')}</button><button id="ask" type="submit">${tr('Ask question','Frage stellen')}</button></div></form><div class="audio-tools"><label><input id="spoken-reply" type="checkbox">${tr('Speak replies','Antworten vorlesen')}</label><button id="replay" disabled>${tr('Replay answer','Antwort abspielen')}</button><button id="mute">${tr('Stop audio','Audio stoppen')}</button><button id="voice-sample">${tr('Audition voice','Stimme anhören')}</button></div><p id="voice-status" role="status"></p><p id="form-error" role="alert"></p><small>${tr('Voice is AI-generated. Recording starts only when you choose it; up to 30 seconds. Questions go to the lesson service. Please omit personal information.','Die Stimme ist KI-generiert. Aufnahme nur nach deiner Auswahl, bis zu 30 Sekunden. Fragen gehen an den Lerndienst. Bitte keine persönlichen Daten.')}</small></div></section>
  <details class="assumptions"><summary>${tr('How the model works','So funktioniert das Modell')} <span>＋</span></summary><div id="assumptions"></div><a href="/methodology?lesson=${id}&lang=${lang}">${tr('Read formulas and assumptions','Formeln und Annahmen lesen')}</a></details>
  <dialog id="video-dialog"><div class="video-heading"><h2>${l.title[lang]} · ${tr('Preset story','Vorgegebenes Beispiel')}</h2><button id="close-video">${tr('Close','Schließen')}</button></div><p>${tr('This video uses a fixed example. Live controls do not change recorded numbers.','Das Video zeigt ein festes Beispiel. Live-Regler ändern die aufgenommenen Zahlen nicht.')}</p><video id="explainer" controls playsinline preload="metadata" poster="/media/${l.scene}-${lang}-poster.jpg"><source src="/media/${l.scene}-${lang}.mp4" type="video/mp4"><track kind="captions" src="/media/${l.scene}-${lang}.vtt" srclang="${lang}" label="${lang==='en'?'English':'Deutsch'}" default></video><details><summary>${tr('Read transcript','Transkript lesen')}</summary><div id="video-transcript"></div></details></dialog>
  </main><footer><span>${tr('Small worlds. Useful ideas.','Kleine Welten. Nützliche Ideen.')}</span><a href="/">${tr('All lessons','Alle Lektionen')}</a><span>n8n · Blender · Babylon.js</span></footer>`;
  $('#language').onchange=e=>{lang=e.target.value;invalidate();render(true);};
  all('[data-lesson]').forEach(el=>el.onclick=e=>{e.preventDefault();switchLesson(el.dataset.lesson);});
  all('[data-input]').forEach(el=>el.onchange=()=>change({[el.dataset.input]:Number(el.value)}));
  all('[data-range]').forEach(el=>el.oninput=()=>change({[el.dataset.range]:Number(el.value)},false));
  all('[data-preset]').forEach(el=>el.onclick=()=>{const p=l.presets[Number(el.dataset.preset)];change(p.values);$('#change-notice').textContent=tr('Changed: ','Geändert: ')+Object.keys(p.values).map(k=>l.fields.find(r=>r[0]===k)?.[lang==='en'?1:2]).join(', ');});
  all('[data-zone]').forEach(el=>el.onclick=()=>focus(el.dataset.zone));
  $('#pause').onclick=()=>{paused=!paused;world?.pause(paused);$('#pause').textContent=paused?tr('Play motion','Bewegung starten'):tr('Pause motion','Bewegung pausieren');$('#pause').setAttribute('aria-pressed',paused);drawFlat(calculateScenario(id,scenario));};
  const reducedControl=document.createElement('label');reducedControl.className='reduced-control';reducedControl.innerHTML=`<input type="checkbox" id="reduced-motion" ${reduced?'checked':''}>${tr('Reduced motion','Weniger Bewegung')}`;$('.world-bottom').append(reducedControl);$('#reduced-motion').onchange=e=>{reduced=e.target.checked;world?.reduced(reduced);if(reduced&&!paused)$('#pause').click();document.body.classList.toggle('reduce-motion',reduced);};
  $('#reset-camera').onclick=()=>{world?.reset();selectedZone=null;all('[data-zone]').forEach(b=>b.setAttribute('aria-pressed','false'));$('#context-text').textContent=tr('Full world view restored. Select a zone to explore.','Gesamtansicht wiederhergestellt. Wähle einen Bereich.');};
  $('#toggle-view').onclick=()=>{flat=!flat;updateView();};
  $('#reset-scenario').onclick=()=>{clearInterval(runTimer);runTimer=null;change(defaults(id));if($('#run-days'))$('#run-days').textContent=tr('Run days','Tage abspielen');world?.reset();};
  $('#save-scenario').onclick=()=>{saved={...scenario};updateComparison();$('#save-scenario').textContent=tr('Replace saved A','Gespeichertes A ersetzen');};
  $('#ask-form').onsubmit=e=>{e.preventDefault();ask($('#question').value);};
  all('[data-question]').forEach(el=>el.onclick=()=>{const q=l.questions[lang][Number(el.dataset.question)];$('#question').value=q;ask(q);});
  $('#context-ask').onclick=()=>{$('#question').value=tr('Explain ','Erkläre ')+(selectedZone?l.zoneLabels[lang][l.zones.indexOf(selectedZone)]:l.title[lang]);$('#question').focus();$('#ask-form').scrollIntoView({behavior:'smooth',block:'center'});};
  $('#mic').onclick=()=>voice.start();$('#record-stop').onclick=()=>voice.stop();$('#record-cancel').onclick=()=>{voice.cancel();$('#voice-status').textContent=tr('Recording canceled. Microphone released.','Aufnahme abgebrochen. Mikrofon freigegeben.');};
  $('#mute').onclick=()=>{voice.stopAudio();$('#spoken-reply').checked=false;$('#voice-status').textContent=tr('Audio stopped.','Audio gestoppt.');};
  $('#replay').onclick=()=>{if(lastAnswer&&lastRequest)voice.speak(lastRequest,lastAnswer.paragraphIds);};
  $('#voice-sample').onclick=()=>{voice.cancel();const r=snapshot('overview');voice.speak(r,['overview']);};
  $('#watch').onclick=()=>openVideo();$('#close-video').onclick=()=>{$('#explainer').pause();$('#video-dialog').close();};$('#explainer').onplay=()=>voice.cancel();
  $('#video-dialog').addEventListener('cancel',()=>$('#explainer').pause());
  if($('#sell-immediately'))$('#sell-immediately').onchange=e=>change({sellImmediately:e.target.checked});
  if($('#advance-day')){$('#advance-day').onclick=advance;$('#run-days').onclick=()=>{if(runTimer){clearInterval(runTimer);runTimer=null;}else runTimer=setInterval(advance,3000);$('#run-days').textContent=runTimer?tr('Pause days','Tage pausieren'):tr('Run days','Tage abspielen');};}
  update();initScene();
}
function switchLesson(next,push=true){invalidate();id=next;scenario=defaults(id);previous=null;saved=null;selectedZone=null;render(push);}
function change(values){try{const next=validateScenario(id,{...scenario,...values});previous={...scenario};scenario=next;invalidate();update();$('#change-notice').textContent=tr('Scenario updated. Results and scene reflect your changes.','Szenario aktualisiert. Zahlen und Szene zeigen deine Änderungen.');}catch(e){$('#change-notice').textContent=e.message;syncInputs();}}
function syncInputs(){all('[data-input]').forEach(el=>el.value=scenario[el.dataset.input]);all('[data-range]').forEach(el=>{const v=scenario[el.dataset.range];if(v>Number(el.max))el.max=v;el.value=v;});if($('#sell-immediately'))$('#sell-immediately').checked=scenario.sellImmediately;}
function advance(){if(scenario.elapsedDays>=30){clearInterval(runTimer);runTimer=null;$('#run-days').textContent=tr('Run days','Tage abspielen');return;}change({elapsedDays:scenario.elapsedDays+1});}
function update(){
  const l=lesson(),c=calculateScenario(id,scenario);syncInputs();world?.update(scenario,c);
  $('#metrics').innerHTML=l.metrics.map(([key,en,de])=>`<div class="metric ${key==='profit'?'main-metric '+(c.profit<0?'negative':''):''}"><span>${tr(en,de)}</span><strong data-metric="${key}">${f(c[key])}</strong></div>`).join('');
  const quick=l.scene==='factory'?[['day',tr('Day','Tag')],['inventory',tr('Parts','Teile')],['produced',tr('Produced today','Heute produziert')]]:[['attendance',tr('Guests','Gäste')],['revenue',tr('Revenue','Umsatz')],['profit',tr('Profit / surplus','Gewinn / Überschuss')]];
  $('#quick-results').innerHTML=quick.map(([k,label])=>`<div><span>${label}</span><strong>${f(c[k])}</strong></div>`).join('');
  $('#scene-badge').textContent=l.scene==='concert'?`${f(c.occupancy)}% ${tr('occupied','belegt')} · ${f(scenario.capacity)} ${tr('places','Plätze')}`:l.scene==='conference'?`${f(c.workshopAccess)}% ${tr('workshop access','Workshopzugang')}`:c.day===0?tr('Ready · advance a day','Bereit · einen Tag weiter'):c.produced===0?tr('LINE STOPPED · waiting for parts','BAND GESTOPPT · wartet auf Teile'):`${tr('Day','Tag')} ${c.day} · ${c.produced} ${tr('vehicles produced','Fahrzeuge produziert')}`;
  if($('#day-label'))$('#day-label').textContent=`${tr('Completed day','Abgeschlossener Tag')} ${c.day} / 30`;
  drawFlat(c);const req=snapshot('overview');showAnswer(preparedLesson(req),req);$('#assumptions').replaceChildren(...Object.values(approvedParagraphs(req)).slice(0,6).map(text=>{const p=document.createElement('p');p.textContent=text;return p;}));
  if(selectedZone)focus(selectedZone,false);updateComparison();
}
function drawFlat(c){
  const cost=c.totalCost??(c.costOfGoodsSold+c.carryingCosts+c.operatingCosts);
  const l=lesson(),count=l.scene==='concert'?Math.ceil(30*c.occupancy/100):l.scene==='conference'?Math.min(30,c.attendance):4;
  $('#flat-view').innerHTML=`<div class="flat-world ${l.scene} ${paused?'motion-paused':''}"><div class="flat-building">${l.icon}<span>${l.title[lang]}</span></div><div class="flat-people">${Array.from({length:count},(_,i)=>`<span class="${l.scene==='factory'?'flat-car':'flat-person'}" style="--i:${i}">${l.scene==='factory'?'🚙':''}</span>`).join('')}</div>${l.scene==='factory'?`<div class="flat-stock">${tr('Parts','Teile')}: ${c.inventory} · ${tr('Production','Produktion')}: ${c.produced}</div>`:''}</div><div class="flat-bars"><label>${tr('Revenue','Umsatz')} <b>${f(c.revenue)}</b></label><div><i style="width:${Math.min(100,100*c.revenue/Math.max(1,c.revenue,cost))}%"></i></div><label>${tr('Costs','Kosten')} <b>${f(cost)}</b></label><div><i class="cost" style="width:${Math.min(100,100*cost/Math.max(1,c.revenue,cost))}%"></i></div></div>`;
  if(l.scene==='factory'&&c.day>0&&c.produced===0)$('#flat-view').classList.add('motion-paused');else $('#flat-view').classList.toggle('motion-paused',paused);
}
function updateView(){$('#venue').hidden=flat;$('#flat-view').hidden=!flat;$('#toggle-view').textContent=flat?'3D':'2D';world?.pause(paused||flat);}
function focus(zone,move=true){selectedZone=zone;const l=lesson(),index=l.zones.indexOf(zone);if(index<0)return;all('[data-zone]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.zone===zone));if(move)world?.focus(zone);const map={entrance:'revenue',stage:'costs',audience:'demand',registration:'overview',speakers:'costs',workshop:'comparison',networking:'demand',catering:'costs',supplier:'comparison',components:'costs',assembly:'demand',finished:'revenue'};$('#context-title').textContent=l.zoneLabels[lang][index];$('#context-text').textContent=approvedParagraphs(snapshot('zone'))[map[zone]];}
function updateComparison(){const el=$('#comparison');if(!saved){el.hidden=true;return;}el.hidden=false;const a=calculateScenario(id,saved),b=calculateScenario(id,scenario);el.innerHTML=`<h2>${tr('Saved A → current B','Gespeichert A → aktuell B')}</h2><p>${tr('Change any input to compare against A. Saved only for this open lesson.','Ändere eine Eingabe zum Vergleich mit A. Nur in dieser geöffneten Lektion gespeichert.')}</p><div class="compare-scroll"><table><thead><tr><th>${tr('Measure','Kennzahl')}</th><th>A</th><th>B</th><th>Δ</th></tr></thead><tbody>${lesson().metrics.map(([k,en,de])=>`<tr><td>${tr(en,de)}</td><td>${f(a[k])}</td><td>${f(b[k])}</td><td>${a[k]===null||b[k]===null?'—':f(b[k]-a[k])}</td></tr>`).join('')}</tbody></table></div>`;}
function showAnswer(answer,request){lastAnswer=answer;lastRequest=request;$('#explanation').textContent=answer.explanation;$('#delivery').textContent=answer.fallbackUsed?tr('Prepared explanation','Vorbereitete Erklärung'):tr('AI-selected explanation · checked numbers','KI-Auswahl · geprüfte Zahlen');$('#replay').disabled=false;}
async function ask(question,inputMode='text'){
  if(!question.trim())return;voice.cancel();document.querySelectorAll('video').forEach(v=>v.pause());const command=parseCommand(question,id,lang);
  if(command){if(command.clarification){$('#form-error').textContent=tr('What exact number should I use? Say or type it with the setting.','Welche genaue Zahl soll ich verwenden? Nenne sie mit der Einstellung.');return;}try{validateScenario(id,{...scenario,[command.field]:command.value});change({[command.field]:command.value});$('#transcript').textContent=tr('Applied: ','Angewendet: ')+lesson().fields.find(r=>r[0]===command.field)[lang==='en'?1:2]+' = '+f(command.value);}catch(e){$('#form-error').textContent=e.message;return;}}
  const req=snapshot(question,inputMode),serial=++turn;$('#ask').disabled=true;$('#ask').textContent=tr('Thinking…','Einen Moment…');$('#form-error').textContent='';
  let answer;
  try{const r=await fetch('/api/lesson',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(req),signal:AbortSignal.timeout(21000)});const j=await r.json();if(serial!==turn)return;if(!r.ok){$('#form-error').textContent=j.error;return;}answer=validateLesson(j,req);}catch{if(serial!==turn)return;answer=preparedLesson(req,'client-fallback');$('#form-error').textContent=tr('Connection unavailable; using prepared content.','Verbindung nicht verfügbar; vorbereitete Erklärung.');}finally{if(serial===turn){$('#ask').disabled=false;$('#ask').textContent=tr('Ask question','Frage stellen');}}
  if(serial!==turn||!answer)return;showAnswer(answer,req);answer.sceneActions.forEach(a=>focus(a.target));if(inputMode==='voice'||$('#spoken-reply').checked)voice.speak(req,answer.paragraphIds);
}
async function initScene(){const canvas=$('#venue');try{const {createVenue}=await import('./scene.js');if(!canvas.isConnected)return;const v=await createVenue(canvas,focus,()=>{},lesson().scene);if(!canvas.isConnected){v.dispose();return;}world=v;world.update(scenario,calculateScenario(id,scenario));world.pause(paused||flat);world.reduced(reduced);canvas.dataset.loaded='true';$('#scene-loading').hidden=true;updateView();}catch(e){console.warn('Scene fallback:',String(e));if(canvas.isConnected){$('#scene-loading').hidden=true;flat=true;updateView();$('#context-text').textContent=tr('3D is unavailable. The animated 2D view and all calculations still work.','3D ist nicht verfügbar. Die animierte 2D-Ansicht und alle Berechnungen funktionieren weiter.');}}}
async function openVideo(){voice.cancel();$('#video-dialog').showModal();try{const r=await fetch(`/media/${lesson().scene}-${lang}.txt`);$('#video-transcript').textContent=r.ok?await r.text():tr('Transcript unavailable.','Transkript nicht verfügbar.');await $('#explainer').play();}catch{$('#video-transcript').textContent=tr('Press Play to start. If playback fails, read the transcript or explore the live lesson.','Zum Starten auf Abspielen drücken. Bei Problemen kannst du den Text lesen oder die Live-Lektion erkunden.');}}
addEventListener('popstate',()=>{const path=normalizeId(location.pathname.split('/')[2]||'concert');lang=new URL(location.href).searchParams.get('lang')==='de'?'de':'en';switchLesson(LESSONS[path]?path:'concert-economics',false);});
if(location.pathname==='/methodology'){$('#app').innerHTML=`<main class="methodology"><a href="/lessons/${id}?lang=${lang}">${tr('Back to lesson','Zur Lektion')}</a><h1>${tr('Behind the model','Hinter dem Modell')}</h1><div>${Object.values(approvedParagraphs(snapshot('overview'))).map(p=>`<p>${p}</p>`).join('')}</div><pre>${lesson().scene==='concert'?'D = floor(M × (p / 20)^(-e))\nA = min(capacity, D)\nCost = production + venueRate × capacity + perGuest × A\nRevenue = p × A\nProfit = revenue − cost':lesson().scene==='conference'?'A = min(expected attendees, capacity)\nRevenue = A × ticket price + sponsor\nAccess = min(A, seats) / A × 100\nSurplus = revenue − all costs':'Receive → produce → consume → sell → accrue → advance\nProduced = min(target, available components)\nContribution = sales − cost of goods sold − holding − operations'}</pre></main>`;}else render();
// Deterministic capture hooks for preset explainer production; never execute model code.
window.lessonCapture={set:(values)=>change(values),focus,seek:t=>world?.seek(t),state:()=>({id,scenario:{...scenario},result:calculateScenario(id,scenario)}),switch:id=>switchLesson(id,false)};
