import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/700.css';
import '@fontsource/manrope/500.css';
import '@fontsource/manrope/800.css';
import './style.css';
import {LESSONS,defaults,normalizeId,validateScenario,calculateScenario,LOCATIONS,MODEL_VERSION,money,crowdScale} from '../shared/registry.js';
import {preparedLesson,approvedParagraphs,validateLesson} from '../shared/lesson.js';
import {parseCommand} from '../shared/commands.js';
import {voiceController} from './voice.js';
import './experience.css';
import {fieldContent,workedExample,setupText,changeExplanation,zoneContent,deriveSceneState} from '../shared/teaching.js';
import './teaching.css';
import './pixel.css';
import './deck.css';
import {breakEven} from '../shared/planning.js';
import {getPlan,setPlan,plannerMarkup,bindPlanner,researchContext} from './planner.js';
let deck,deckSerial=0,savedPlan=null,savedVariables=[],undoPlanning=null;
function updateDeck(){deck?.update(scenario,paused||reduced);}
async function initDeck(){if(deck&&$('#control-deck')?.dataset.loaded==='true'){updateDeck();return;}const serial=++deckSerial,canvas=$('#control-deck');deck?.dispose();deck=null;try{const {createDeck}=await import('./deck.js');if(!canvas?.isConnected||serial!==deckSerial)return;const d=await createDeck(canvas);if(!canvas.isConnected||serial!==deckSerial){d.dispose();return;}deck=d;updateDeck();}catch{if(canvas?.isConnected){canvas.hidden=true;canvas.nextElementSibling.textContent=tr('Deck animation unavailable. All controls still work.','Deck-Animation nicht verfügbar. Alle Regler funktionieren.');}}}


const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const url=new URL(location.href);let lang=url.searchParams.get('lang')==='de'?'de':'en';
let id=normalizeId(location.pathname.split('/')[2]||url.searchParams.get('lesson')||'concert');if(!LESSONS[id])id='concert-economics';
let scenario=defaults(id),previous=null,saved=null,revision=0,turn=0,world,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,paused=reduced,flat=false,lastAnswer,lastRequest,selectedZone=null,sceneAvailable=false,transcriptMode='text',changedFields=[],undoState=null,dragStart=null;
let visibleVariables=new Set(),undoVariables=null,announcementTimer;
const optionalKeys=['productionBudget','venueRate','perGuest','promotionBudget','promotionBoost','sponsorship','elasticity'];
const cash=n=>money(n,lang);
const sessionId=crypto.randomUUID();const tr=(en,de)=>lang==='de'?de:en;const f=n=>n===null?tr('N/A','n. a.'):new Intl.NumberFormat(lang==='de'?'de-DE':'en-US',{maximumFractionDigits:2}).format(n);
const lesson=()=>LESSONS[id];const snapshot=(question,inputMode='text')=>({requestId:crypto.randomUUID(),sessionId,topicId:id,language:lang,question,scenario:{...scenario},previousScenario:previous?{...previous}:null,scenarioRevision:revision,inputMode,researchContext:researchContext(),savedScenario:saved?{...saved}:null,modelVersion:MODEL_VERSION,currency:'USD'});
const voice=voiceController({language:()=>lang,onTranscript:text=>{if($('#question')){$('#question').value=text;$('#transcript').textContent=tr('Recognized speech — correct the text, then send.','Erkannter Text — bitte prüfen, dann senden.');transcriptMode='voice';$('#question').focus();}},onStatus:text=>{if($('#voice-status'))$('#voice-status').textContent=text;},onRecording:yes=>{if($('#mic')){$('#mic').disabled=yes;$('#record-stop').hidden=!yes;$('#record-cancel').hidden=!yes;$('#mic').classList.toggle('recording',yes);}}});

function invalidate(){turn++;revision++;lastAnswer=null;lastRequest=null;voice.cancel();if($('#ask')){$('#ask').disabled=false;$('#ask').textContent=tr('Send','Senden');}if($('#replay'))$('#replay').disabled=true;}
function field(row){const key=row[0],meta=fieldContent(id,key,lang),value=scenario[key];const monetary=['ticketPrice','productionBudget','venueRate','perGuest','promotionBudget','sponsorship'].includes(key);return `<div class="field" data-field="${key}"><label for="field-${key}">${tr(row[1],row[2])}</label>${optionalKeys.includes(key)?`<button class="remove-variable" data-remove="${key}" aria-label="${tr('Remove and reset','Entfernen und zurücksetzen')} ${tr(row[1],row[2])}">×</button>`:''}<div class="field-value"><input id="field-${key}" data-input="${key}" type="number" min="${meta.min}" max="${meta.max}" step="${meta.step}" value="${value}" inputmode="decimal" aria-describedby="help-${key} error-${key}"/><small>${monetary?'$':meta.unit}</small></div><small class="field-help" id="help-${key}">${key==='promotionBudget'?tr('Spending more does not guarantee more buyers. Set the audience boost you want to test.','Mehr Ausgaben garantieren keine zusätzlichen Gäste. Teste einen angenommenen Nachfragezuwachs.'):meta.help}</small><small class="field-error" id="error-${key}" role="alert"></small><input aria-label="${meta.label} ${tr('slider','Regler')}" data-range="${key}" type="range" min="${meta.min}" max="${Math.max(value,key==='capacity'?2000:key==='demand'?2000:key==='manualAttendance'?scenario.capacity:monetary?key==='ticketPrice'?100:key==='venueRate'||key==='perGuest'?30:10000:meta.max)}" step="${meta.step}" value="${value}"/><small class="worked-example" data-example="${key}"></small>${key==='elasticity'?`<div class="sensitivity">${[[.5,tr('Low','Niedrig')],[1,tr('Medium','Mittel')],[2,tr('High','Hoch')]].map(([n,t])=>`<button type="button" data-sensitivity="${n}">${t}</button>`).join('')}</div>`:''}</div>`;}
function dashboard(){const row=k=>lesson().fields.find(r=>r[0]===k);return `<h2>${tr('Mix Your Margins','Mixe deine Gewinne')}</h2><p>${tr('Work the controls. See what pays. Drag a fader or type a number.','Dein Konzert-Dashboard. Bewege einen Regler oder gib eine Zahl ein.')}</p><div class="deck-display"><canvas id="control-deck" aria-hidden="true"></canvas><div class="deck-caption"><span>PRICE / MIX</span><span>CAPACITY / MIX</span></div></div><div class="deck-channels">${field(row('ticketPrice'))}${field(row('capacity'))}</div><p id="break-even" class="break-even" aria-live="polite"></p><label for="location">${tr('Venue setup','Veranstaltungsprofil')}</label><select id="location">${Object.entries(LOCATIONS).map(([k,v])=>`<option value="${k}" ${scenario.location===k?'selected':''}>${v[lang]}</option>`).join('')}</select><small>${tr('Illustrative location presets, not live venue quotes.','Beispielhafte Annahmen, keine aktuellen Veranstaltungsangebote.')}</small><p id="profile-summary"></p><label for="audience-mode">${tr('Audience','Publikum')}</label><select id="audience-mode"><option value="estimated" ${scenario.audienceMode==='estimated'?'selected':''}>${tr('Estimate from ticket price','Anhand des Ticketpreises schätzen')}</option><option value="manual" ${scenario.audienceMode==='manual'?'selected':''}>${tr('Set attendance myself','Gästezahl selbst festlegen')}</option></select><p id="audience-help"></p><div id="audience-field">${field(row(scenario.audienceMode==='manual'?'manualAttendance':'demand'))}</div><p id="capacity-warning" role="status"></p><label for="add-variable">${tr('Add a variable…','Variable hinzufügen…')}</label><select id="add-variable"><option value="">${tr('Choose a variable','Variable auswählen')}</option>${optionalKeys.filter(k=>!visibleVariables.has(k)).map(k=>`<option value="${k}">${row(k)[lang==='de'?2:1]}</option>`).join('')}</select><div id="optional-fields">${optionalKeys.filter(k=>visibleVariables.has(k)).map(k=>field(row(k))).join('')}</div>${plannerMarkup(tr)}`;}
function bindDashboard(){
 bindPlanner($('.dashboard'),tr,lang);initDeck();
 all('[data-input]').forEach(el=>el.onchange=()=>{const key=el.dataset.input;try{if(el.value.trim()==='')throw new Error(tr('Enter a number; your previous setting is retained.','Gib eine Zahl ein; der bisherige Wert bleibt erhalten.'));validateScenario(id,{...scenario,[key]:Number(el.value)});el.setAttribute('aria-invalid','false');change({[key]:Number(el.value)});}catch(e){el.setAttribute('aria-invalid','true');$('#error-'+key).textContent=lang==='de'?`Bitte eine Zahl von ${el.min} bis ${el.max} eingeben.`:e.message;}});
 all('[data-range]').forEach(el=>{el.onpointerdown=()=>{dragStart={...scenario};};el.onkeydown=()=>{dragStart??={...scenario};};el.oninput=()=>change({[el.dataset.range]:Number(el.value)});el.onchange=()=>{dragStart=null;};el.onblur=()=>{dragStart=null;};});
 $('#location').onchange=e=>{const key=e.target.value;change({...(LOCATIONS[key].values||{}),location:key,...(key==='custom'?{}:{profile:key})});refreshDashboard();};
 $('#audience-mode').onchange=e=>{change({audienceMode:e.target.value});refreshDashboard();};
 $('#add-variable').onchange=e=>{if(e.target.value){visibleVariables.add(e.target.value);refreshDashboard();}};
 all('[data-remove]').forEach(el=>el.onclick=()=>{const key=el.dataset.remove;const oldVariables=new Set(visibleVariables),oldScenario={...scenario};visibleVariables.delete(key);const value=LOCATIONS[scenario.profile].values[key]??defaults(id)[key];change({[key]:value});undoState=oldScenario;undoVariables=oldVariables;refreshDashboard();});
 all('[data-sensitivity]').forEach(el=>el.onclick=()=>change({elasticity:Number(el.dataset.sensitivity)}));const sensitivity=$('[data-field=elasticity] .sensitivity');if(sensitivity){sensitivity.innerHTML=`<select id="sensitivity-level" aria-label="${tr('Price sensitivity level','Stufe der Preissensibilität')}">${[[.5,tr('Low','Niedrig')],[1,tr('Medium','Mittel')],[2,tr('High','Hoch')],['custom',tr('Custom','Eigener Wert')]].map(([v,label])=>`<option value="${v}" ${scenario.elasticity===v||v==='custom'&&![.5,1,2].includes(scenario.elasticity)?'selected':''}>${label}</option>`).join('')}</select>`;$('#sensitivity-level').onchange=e=>{if(e.target.value!=='custom')change({elasticity:Number(e.target.value)});else $('#field-elasticity').focus();};}
}
function refreshDashboard(){ const oldDeck=deck?$('.deck-display'):null;$('.decision-panel .dashboard').innerHTML=dashboard();if(oldDeck)$('.deck-display').replaceWith(oldDeck);bindDashboard();update();}
function render(push=false){
  deckSerial++;deck?.dispose();deck=null;flat=false;world?.dispose();world=null;sceneAvailable=false;voice.cancel();turn++;document.documentElement.lang=lang;
  const l=lesson();if(push)history.pushState({},'',`/lessons/${id}?lang=${lang}`);
  document.title=l.title[lang]+' — The Economics of Everything';
  $('#app').innerHTML=`<header class="site-header"><a class="brand" href="/"><span class="brand-mark">e<span>•</span></span><span>The Economics<br>of Everything</span></a><span class="header-lab">${tr('SMALL WORLDS. REAL INSIGHTS.','KLEINE WELTEN. ECHTE ERKENNTNISSE.')}</span><select id="language" aria-label="Language / Sprache"><option value="en" ${lang==='en'?'selected':''}>English</option><option value="de" ${lang==='de'?'selected':''}>Deutsch</option></select></header>
  <main class="experience"><div class="eyebrow concert-heading">${tr('The concert','Das Konzert')}</div>
  <div class="compact-title"><div><h1>${l.question[lang]}</h1><p id="setup">${tr('Set the price. Build the crowd. See what pays. Adjust your ticket price, venue and event costs, then watch the dance floor and neon signs respond. Can you put on a great night and still make a profit?','Setze den Preis. Gewinne Gäste. Sieh, was sich lohnt. Ändere Ticketpreis, Saal und Kosten und beobachte Tanzfläche und Neonanzeigen. Schaffst du einen großartigen Abend mit Gewinn?')}</p><small class="money-note">${tr('An interactive teaching simulation · All amounts in US dollars ($).','Interaktive Lernsimulation · Alle Beträge in US-Dollar ($).')}</small></div><button id="watch" class="primary">▶ ${tr('Watch the short story','Die Kurzgeschichte ansehen')}</button></div>
  <div class="experience-grid"><section class="world-panel"><div class="world-top"><span class="eyebrow">${tr('Your concert, live','Dein Konzert, live')}</span><div class="world-tools"><button id="pause" aria-pressed="${paused}">${paused?tr('Play motion','Bewegung starten'):tr('Pause motion','Bewegung pausieren')}</button></div></div><div class="canvas-wrap"><canvas id="venue" aria-label="${tr('Live pixel-art concert. Dashboard controls update the audience.','Live-Konzert in Pixel-Art. Das Dashboard verändert das Publikum.')}" tabindex="0"></canvas><div id="scene-loading" role="status">${tr('Opening your world…','Deine Welt wird geöffnet…')}</div><div id="quick-results" class="neon-signs" aria-live="off"></div><button id="retry-scene" hidden>${tr('Retry scene','Szene erneut laden')}</button><div class="scene-badge" id="scene-badge"></div></div><div class="world-bottom"><span id="view-instruction">${tr('Select a scene area to explore','Wähle einen Szenenbereich')}</span><span><span id="crowd-scale"></span></span></div>
  <div class="hotspots">${l.zones.map((z,i)=>`<button data-zone="${z}" aria-pressed="false">${String(i+1).padStart(2,'0')} ${l.zoneLabels[lang][i]}</button>`).join('')}</div><div class="context-card" aria-live="polite"><div><span class="eyebrow" id="context-title">${tr('EXPLORE A PART OF THE WORLD','ERKUNDE EINEN BEREICH')}</span><p id="context-text">${tr('Select a labeled zone above. The camera will move closer and its explanation will appear here.','Wähle oben einen Bereich. Die Kamera fährt näher heran und hier erscheint die Erklärung.')}</p></div><button id="experiment" hidden></button><button id="context-ask">${tr('Ask about this','Dazu eine Frage stellen')}</button></div>
  </section>
  <aside class="decision-panel"><div class="dashboard">${dashboard()}</div><div class="scenario-actions"><button id="reset-scenario">${tr('Reset concert','Konzert zurücksetzen')}</button><button id="save-scenario">${tr('Save this mix','Diesen Mix speichern')}</button></div></aside></div>
  <section class="change-card"><h2>${tr('Your last move','Deine letzte Änderung')}</h2><p id="causal-change"></p><span id="metric-announcement" class="sr-only" role="status" aria-live="polite"></span><p id="change-notice" role="status"></p><button id="undo" disabled>${tr('Undo last change','Letzte Änderung rückgängig')}</button></section>
  <details class="result-card"><summary>${tr('Your costs and assumptions','Deine Kosten und Annahmen')}</summary><div id="breakdown"></div><div id="metrics"></div><small>${tr('This teaching model excludes tax, financing, refunds and other unmodeled costs.','Dieses Lernmodell schließt Steuern, Finanzierung, Rückerstattungen und weitere Kosten aus.')}</small></details>
  <section id="comparison" class="comparison" hidden></section>
  <section class="tutor-section"><div><div class="eyebrow">${tr('ASK. LISTEN. TRY SOMETHING.','FRAGEN. ZUHÖREN. AUSPROBIEREN.')}</div><h2>${tr('Ask your concert coach','Frage deinen Konzert-Coach')}</h2><p>${tr('Ask why a number changed, or explore your next move.','Frage, warum sich eine Zahl geändert hat, oder erkunde deinen nächsten Schritt.')}</p><div class="question-chips">${l.questions[lang].map((q,i)=>`<button data-question="${i}">${q}</button>`).join('')}</div></div><div class="tutor-card"><div class="tutor-heading"><span class="tutor-avatar">e•</span><span id="delivery">${tr('Prepared explanation','Vorbereitete Erklärung')}</span></div><p id="explanation" aria-live="polite"></p><p id="transcript"></p><form id="ask-form"><label for="question">${tr('Your question','Deine Frage')}</label><textarea id="question" maxlength="600" rows="2" placeholder="${l.questions[lang][0]}" required></textarea><div class="form-bottom"><button type="button" id="mic" aria-label="${tr('Speak a question','Frage sprechen')}" title="${tr('Speak a question','Frage sprechen')}"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/></svg></button><button type="button" id="record-stop" hidden>${tr('Stop recording','Aufnahme stoppen')}</button><button type="button" id="record-cancel" hidden>${tr('Cancel','Abbrechen')}</button><button id="ask" type="submit">${tr('Send','Senden')}</button></div></form><div class="audio-tools"><label><input id="spoken-reply" type="checkbox">${tr('Speak replies','Antworten vorlesen')}</label><button id="replay" disabled>${tr('Replay answer','Antwort abspielen')}</button><button id="mute">${tr('Stop audio','Audio stoppen')}</button>${url.searchParams.has('review')?`<button id="voice-sample">${tr('Audition voice','Stimme anhören')}</button>`:''}</div><p id="voice-status" role="status"></p><p id="form-error" role="alert"></p><small>${tr('Voice is AI-generated. Recording starts only when you choose it; up to 30 seconds. Questions go to the lesson service. Please omit personal information.','Die Stimme ist KI-generiert. Aufnahme nur nach deiner Auswahl, bis zu 30 Sekunden. Fragen gehen an den Lerndienst. Bitte keine persönlichen Daten.')}</small></div></section>
  <details class="assumptions"><summary>${tr('How the model works','So funktioniert das Modell')} <span>＋</span></summary><div id="assumptions"></div><a href="/methodology?lesson=${id}&lang=${lang}">${tr('Read formulas and assumptions','Formeln und Annahmen lesen')}</a></details>
  <dialog id="video-dialog"><div class="video-heading"><h2>${l.title[lang]} · ${tr('Preset story','Vorgegebenes Beispiel')}</h2><button id="close-video">${tr('Close','Schließen')}</button></div><p>${tr('This video uses a fixed example. Live controls do not change recorded numbers.','Das Video zeigt ein festes Beispiel. Live-Regler ändern die aufgenommenen Zahlen nicht.')}</p><video id="explainer" controls playsinline preload="metadata" poster="/media/${l.scene}-${lang}-poster.jpg"><source src="/media/${l.scene}-${lang}.mp4" type="video/mp4"><track kind="captions" src="/media/${l.scene}-${lang}.vtt" srclang="${lang}" label="${lang==='en'?'English':'Deutsch'}" default></video><details><summary>${tr('Read transcript','Transkript lesen')}</summary><div id="video-transcript"></div></details></dialog>
  </main><footer><span>${tr('Small worlds. Useful ideas.','Kleine Welten. Nützliche Ideen.')}</span><a href="/">${tr('The concert','Das Konzert')}</a><span>n8n · Blender · Babylon.js</span></footer>`;
  $('#language').onchange=e=>{lang=e.target.value;invalidate();render(true);};
  all('[data-lesson]').forEach(el=>el.onclick=e=>{e.preventDefault();switchLesson(el.dataset.lesson);});
  bindDashboard();
  all('[data-zone]').forEach(el=>el.onclick=()=>focus(el.dataset.zone));
  $('#pause').onclick=()=>{paused=!paused;world?.pause(paused);updateDeck();$('#pause').textContent=paused?tr('Play motion','Bewegung starten'):tr('Pause motion','Bewegung pausieren');$('#pause').setAttribute('aria-pressed',paused);drawFlat(calculateScenario(id,scenario));};
  const reducedControl=document.createElement('label');reducedControl.className='reduced-control';reducedControl.innerHTML=`<input type="checkbox" id="reduced-motion" ${reduced?'checked':''}>${tr('Reduced motion','Weniger Bewegung')}`;$('.world-bottom').append(reducedControl);document.body.classList.toggle('reduce-motion',reduced);$('#reduced-motion').onchange=e=>{reduced=e.target.checked;world?.reduced(reduced);updateDeck();if(reduced&&!paused)$('#pause').click();document.body.classList.toggle('reduce-motion',reduced);};
  $('#undo').onclick=()=>{if(undoState){const values=undoState;const vars=undoVariables;const planning=undoPlanning;undoState=null;change(values,true);if(vars)visibleVariables=vars;if(planning)setPlan(planning);undoPlanning=null;undoState=null;undoVariables=null;refreshDashboard();$('#undo').disabled=true;}};
  $('#experiment').onclick=()=>{const z=zoneContent(id,selectedZone,scenario,calculateScenario(id,scenario),lang);change(z.values);};
  $('#retry-scene').onclick=()=>{world?.dispose();world=null;$('#retry-scene').hidden=true;$('#scene-loading').hidden=false;initScene();};
  $('#reset-scenario').onclick=()=>{const oldPlan=getPlan();const vars=new Set(visibleVariables);visibleVariables.clear();saved=null;savedPlan=null;setPlan(null);$('#save-scenario').textContent=tr('Save this mix','Diesen Mix speichern');localStorage.removeItem('concert-mix');change(defaults(id),true);undoVariables=vars;undoPlanning=oldPlan;refreshDashboard();};
  $('#save-scenario').onclick=()=>{saved={...scenario};savedPlan=getPlan();savedVariables=[...visibleVariables];localStorage.setItem('concert-mix',JSON.stringify({saveVersion:2,planning:savedPlan,modelVersion:MODEL_VERSION,scenarioRevision:revision,currency:'USD',scenario:saved,result:calculateScenario(id,saved),visibleVariables:[...visibleVariables]}));updateComparison();$('#save-scenario').textContent=tr('Replace saved mix','Gespeicherten Mix ersetzen');};
  $('#ask-form').onsubmit=e=>{e.preventDefault();ask($('#question').value,transcriptMode);transcriptMode='text';};
  all('[data-question]').forEach(el=>el.onclick=()=>{const q=l.questions[lang][Number(el.dataset.question)];$('#question').value=q;ask(q);});
  $('#context-ask').onclick=()=>{$('#question').value=tr('Explain ','Erkläre ')+(selectedZone?l.zoneLabels[lang][l.zones.indexOf(selectedZone)]:l.title[lang]);$('#question').focus();$('#ask-form').scrollIntoView({behavior:'smooth',block:'center'});};
  $('#mic').onclick=()=>voice.start();$('#record-stop').onclick=()=>voice.stop();$('#record-cancel').onclick=()=>{voice.cancel();$('#voice-status').textContent=tr('Recording canceled. Microphone released.','Aufnahme abgebrochen. Mikrofon freigegeben.');};
  $('#mute').onclick=()=>{voice.stopAudio();$('#spoken-reply').checked=false;$('#voice-status').textContent=tr('Audio stopped.','Audio gestoppt.');};
  $('#replay').onclick=()=>{if(lastAnswer&&lastRequest)voice.speak(lastRequest,lastAnswer.paragraphIds);};
  if($('#voice-sample'))$('#voice-sample').onclick=()=>{voice.cancel();const r=snapshot('overview');voice.speak(r,['overview']);};
  $('#watch').onclick=()=>openVideo();$('#close-video').onclick=()=>{$('#explainer').pause();$('#video-dialog').close();};$('#explainer').onplay=()=>voice.cancel();
  $('#video-dialog').addEventListener('cancel',()=>$('#explainer').pause());
  arrangeTeachingLayout();update();initScene();
}
function arrangeTeachingLayout(){const column=document.createElement('div');column.className='world-column';column.append($('.world-panel'),$('.change-card'));$('.experience-grid').prepend(column);const explore=document.createElement('details');explore.className='explore-panel';explore.innerHTML=`<summary>${tr('Explore the economics','Wirtschaftliche Zusammenhänge erkunden')}</summary>`;explore.append($('.hotspots'),$('.context-card'));$('.result-card').after(explore);$('#view-instruction').textContent=tr('Pause freezes motion; your decisions still update the crowd and signs.','Pause stoppt die Bewegung; Änderungen aktualisieren weiterhin Publikum und Anzeigen.');}
function metricLabel(key,en,de,c){return tr(en,de);}
function updateTeaching(c){
 const be=breakEven(scenario);$('#break-even').textContent=be.margin<0?tr('Each extra guest reduces profit; a minimum headcount threshold does not apply.','Jeder weitere Gast senkt den Gewinn; eine Mindestgästezahl ist nicht anwendbar.')+(be.covered?tr(' Sponsorship covers fixed costs.',' Sponsoren decken die Fixkosten.'):''):be.margin===0?tr('Guest count cannot improve the result. ','Die Gästezahl kann das Ergebnis nicht verbessern. ')+(be.covered?tr('Fixed costs are covered.','Fixkosten sind gedeckt.'):tr('Fixed costs are not covered.','Fixkosten sind nicht gedeckt.')):tr('Guests needed to break even: ','Gäste bis zur Gewinnschwelle: ')+f(be.guests)+'. '+(be.guests>scenario.capacity?tr('Break-even is above this venue’s capacity.','Die Gewinnschwelle liegt über der Kapazität.'):c.attendance<be.guests?tr(`${f(be.guests-c.attendance)} more guests needed.`,`${f(be.guests-c.attendance)} weitere Gäste benötigt.`):tr('At this price; not predicted demand.','Bei diesem Preis; keine Nachfrageprognose.'));updateDeck();
 $('#causal-change').textContent=changeExplanation(id,scenario,previous,lang);$('#undo').disabled=!undoState;
 all('[data-example]').forEach(e=>e.textContent=workedExample(id,e.dataset.example,scenario,c,lang));
 if($('#sensitivity-level'))$('#sensitivity-level').value=[.5,1,2].includes(scenario.elasticity)?String(scenario.elasticity):'custom';$('#location').value=scenario.location;$('#audience-mode').value=scenario.audienceMode;
 $('#profile-summary').textContent=tr('Venue assumptions: ','Veranstaltungsannahmen: ')+`${f(scenario.demand)} ${tr('interested at $20','Interessierte bei $20')} · ${cash(scenario.productionBudget)} ${tr('production','Produktion')} · ${cash(scenario.venueRate)} / ${tr('place','Platz')} · ${cash(scenario.perGuest)} / ${tr('guest','Gast')}`;
 $('#audience-help').textContent=scenario.audienceMode==='manual'?tr('You choose the crowd size. Ticket-price changes affect revenue, while this headcount stays fixed.','Du wählst die Gästezahl. Preisänderungen beeinflussen den Umsatz, während diese Zahl gleich bleibt.'):tr('At a $20 ticket price, this many people would want to come. Changing the price changes the estimate.','So viele Menschen möchten bei einem Ticketpreis von $20 kommen. Der Preis verändert die Schätzung.');
 $('#capacity-warning').textContent=scenario.audienceMode==='manual'&&scenario.manualAttendance>scenario.capacity?tr(`You requested ${f(scenario.manualAttendance)} guests; this venue holds ${f(scenario.capacity)}. Attendance is capped at ${f(c.attendance)}.`,`Du hast ${f(scenario.manualAttendance)} Gäste angefragt; der Saal fasst ${f(scenario.capacity)}. Die Gästezahl ist auf ${f(c.attendance)} begrenzt.`):'';
 all('[data-input="promotionBoost"],[data-range="promotionBoost"]').forEach(el=>el.disabled=scenario.audienceMode==='manual');if($('#help-promotionBoost'))$('#help-promotionBoost').textContent=scenario.audienceMode==='manual'?tr('Stored but unused in manual mode.','Gespeichert, aber im manuellen Modus nicht verwendet.'):tr('An explicit assumed increase in interested guests; spending alone guarantees nothing.','Ausdrücklich angenommener Nachfragezuwachs; Ausgaben allein garantieren nichts.');
 const rows=[[tr('Ticket revenue','Ticketumsatz'),c.ticketRevenue],[tr('Sponsor contribution','Sponsorenbeitrag'),c.sponsorship],[tr('DJ, stage & sound','DJ, Bühne & Ton'),c.productionCost],[tr('Venue hire total','Gesamte Saalmiete'),c.venueCost],[tr('Guest services','Leistungen für Gäste'),c.variableCost],[tr('Promotion budget','Werbebudget'),c.promotionCost]];
 $('#breakdown').innerHTML=rows.map(([label,value])=>`<div class="cost-line"><span>${label}</span><b>${cash(value)}</b></div>`).join('')+`<p>${tr('Assumed promotion boost','Angenommener Werbezuwachs')}: ${f(scenario.promotionBoost)}% ${scenario.audienceMode==='manual'?tr('(unused in manual mode)','(im manuellen Modus ungenutzt)'):''}. ${tr('Price sensitivity','Preissensibilität')}: ${f(scenario.elasticity)}.</p>`;
}
function switchLesson(next,push=true){dragStart=null;undoState=null;invalidate();id=next;scenario=defaults(id);previous=null;saved=null;selectedZone=null;render(push);}
function change(values,restore=false){undoPlanning=null;try{let next=validateScenario(id,{...scenario,...values});if(!restore&&!Object.hasOwn(values,'location')&&['demand','productionBudget','venueRate','perGuest'].some(k=>Object.hasOwn(values,k)&&values[k]!==scenario[k]))next.location='custom';changedFields=Object.keys(next).filter(k=>scenario[k]!==next[k]);if(!changedFields.length){updateComparison();return;};undoVariables=new Set(visibleVariables);undoState={...(dragStart||scenario)};previous={...(dragStart||scenario)};scenario=next;invalidate();update();$('#change-notice').textContent='';}catch(e){$('#change-notice').textContent=lang==='de'?'Bitte gültige Zahlen innerhalb der angegebenen Grenzen eingeben. Die bisherigen Einstellungen bleiben erhalten.':e.message;syncInputs();}}
function syncInputs(){all('[data-input]').forEach(el=>el.value=scenario[el.dataset.input]);all('[data-range]').forEach(el=>{const v=scenario[el.dataset.range];if(v>Number(el.max))el.max=v;el.value=v;});}
function update(){
  const l=lesson(),c=calculateScenario(id,scenario);syncInputs();world?.update(scenario,c,deriveSceneState(id,scenario,c,selectedZone));
  $('#metrics').innerHTML=l.metrics.map(([key,en,de])=>`<div class="metric ${key==='profit'?'main-metric '+(c.profit<0?'negative':''):''}"><span>${metricLabel(key,en,de,c)}</span><strong data-metric="${key}">${['revenue','totalCost','profit'].includes(key)?cash(c[key]):f(c[key])}</strong></div>`).join('');
  const signs=[[tr('Audience','Publikum'),`${f(c.attendance)} / ${f(scenario.capacity)}`,`${f(c.occupancy)}% ${tr('full','belegt')}`],[tr('Revenue','Einnahmen'),cash(c.revenue),tr('Tickets + sponsorship','Tickets + Sponsoren')],[tr('Total costs','Gesamtkosten'),cash(c.totalCost),tr('All modeled costs','Alle modellierten Kosten')],[c.profit<0?tr('Loss','Verlust'):tr('Profit','Gewinn'),cash(c.profit),tr('Revenue − costs','Einnahmen − Kosten')],['ROI',c.returnOnCost===null?'—':new Intl.NumberFormat(lang==='de'?'de-DE':'en-US',{minimumFractionDigits:1,maximumFractionDigits:1}).format(c.returnOnCost)+'%',c.returnOnCost===null?tr('ROI needs a cost greater than $0.','ROI benötigt Kosten über $0.'):tr('Profit ÷ total costs × 100','Gewinn ÷ Gesamtkosten × 100')]];
  $('#quick-results').innerHTML=signs.map(([label,value,help],i)=>`<div class="neon-sign ${i===3&&c.profit<0?'negative':''}" tabindex="0" title="${help}"><span>${label}</span><strong style="--mobile-value-size:${Math.min(18,166/String(value).length)}px;--desktop-value-size:${Math.min(29,220/String(value).length)}px">${value}</strong><small>${help}</small><details class="metric-help"><summary aria-label="${tr('Help: ','Hilfe: ')}${label}">ⓘ</summary><p>${help}${i===4?' '+tr('An ROI of 20% means $0.20 profit for every $1 spent. This is return on event costs, not profit margin.','Ein ROI von 20% bedeutet $0,20 Gewinn pro ausgegebenem $1. Dies ist Kostenrendite, keine Gewinnmarge.'):''}</p></details></div>`).join('');
  const scale=crowdScale(scenario.capacity,c.attendance);$('#crowd-scale').textContent=scale.peoplePerFigure>1?tr(`Crowd illustration: each figure represents up to ${scale.peoplePerFigure} guests.`,`Publikumsdarstellung: Jede Figur steht für bis zu ${scale.peoplePerFigure} Gäste.`):tr('One figure per guest.','Eine Figur pro Gast.');
  updateTeaching(c);clearTimeout(announcementTimer);announcementTimer=setTimeout(()=>{if($('#metric-announcement'))$('#metric-announcement').textContent=tr('Audience: ','Publikum: ')+f(c.attendance)+'. '+tr('Profit: ','Gewinn: ')+cash(c.profit)+'.';},400);
  $('#scene-badge').textContent=`${f(c.occupancy)}% ${tr('occupied','belegt')} · ${f(scenario.capacity)} ${tr('places','Plätze')}`;
  drawFlat(c);const req=snapshot('overview');showAnswer(preparedLesson(req),req);$('#assumptions').replaceChildren(...Object.values(approvedParagraphs(req)).slice(0,6).map(text=>{const p=document.createElement('p');p.textContent=text;return p;}));
  if(selectedZone)focus(selectedZone,false);updateComparison();
}
function drawFlat(){}
function updateView(){world?.pause(paused);}
function focus(zone,move=true){if(move&&!document.body.classList.contains('capture-mode'))$('.explore-panel').open=true;selectedZone=zone;const l=lesson(),index=l.zones.indexOf(zone);if(index<0)return;all('[data-zone]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.zone===zone));if(move)world?.focus(zone);const c=calculateScenario(id,scenario),z=zoneContent(id,zone,scenario,c,lang);$('#context-title').textContent=tr('Looking at: ','Im Blick: ')+l.zoneLabels[lang][index];$('#context-text').textContent=z.status+' '+z.meaning;$('#experiment').hidden=false;$('#experiment').textContent=tr('Try: ','Ausprobieren: ')+Object.entries(z.values).map(([k,v])=>fieldContent(id,k,lang).label+' → '+f(v)+' '+fieldContent(id,k,lang).unit).join('; ')+('');drawFlat(c);}
function updateComparison(){const el=$('#comparison');if(!saved){el.hidden=true;return;}el.hidden=false;const a=calculateScenario(id,saved),b=calculateScenario(id,scenario);el.innerHTML=`<h2>${tr('Compared with your saved mix','Vergleich mit deinem gespeicherten Mix')}</h2><button id="restore-mix">${tr('Restore saved mix','Gespeicherten Mix laden')}</button><button id="export-mix">${tr('Export mix','Mix exportieren')}</button><p>${tr('Change any input to compare against A. Stored on this device.','Ändere eine Eingabe zum Vergleich mit A. Auf diesem Gerät gespeichert.')}</p><div class="compare-scroll"><table><thead><tr><th>${tr('Measure','Kennzahl')}</th><th>${tr('Saved','Gespeichert')}</th><th>${tr('Current','Aktuell')}</th><th>${tr('Difference','Differenz')}</th></tr></thead><tbody>${lesson().metrics.map(([k,en,de])=>`<tr><td>${tr(en,de)}</td><td>${['revenue','totalCost','profit'].includes(k)?cash(a[k]):f(a[k])}</td><td>${['revenue','totalCost','profit'].includes(k)?cash(b[k]):f(b[k])}</td><td>${a[k]===null||b[k]===null?'—':['revenue','totalCost','profit'].includes(k)?cash(b[k]-a[k]):f(b[k]-a[k])}</td></tr>`).join('')}</tbody></table></div>`;$('#restore-mix').onclick=()=>{const oldPlan=getPlan();change(saved,true);setPlan(savedPlan);undoPlanning=oldPlan;visibleVariables=new Set(savedVariables);refreshDashboard();};$('#export-mix').onclick=()=>{const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify({saveVersion:2,planning:savedPlan,modelVersion:MODEL_VERSION,scenarioRevision:revision,currency:'USD',scenario:saved,result:calculateScenario(id,saved)},null,2)],{type:'application/json'}));link.download='concert-mix.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);};}
function showAnswer(answer,request){lastAnswer=answer;lastRequest=request;$('#explanation').textContent=answer.explanation;$('#delivery').textContent=answer.fallbackUsed?tr('Prepared explanation','Vorbereitete Erklärung'):tr('Concert coach · checked numbers','Konzert-Coach · geprüfte Zahlen');$('#replay').disabled=false;}
async function ask(question,inputMode='text'){
  if(!question.trim())return;voice.cancel();document.querySelectorAll('video').forEach(v=>v.pause());const command=parseCommand(question,id,lang);
  if(command){if(command.clarification){$('#form-error').textContent=tr('What exact number should I use? Say or type it with the setting.','Welche genaue Zahl soll ich verwenden? Nenne sie mit der Einstellung.');return;}try{validateScenario(id,{...scenario,[command.field]:command.value});change({[command.field]:command.value});$('#transcript').textContent=tr('Applied (Undo is available): ','Angewendet (rückgängig möglich): ')+fieldContent(id,command.field,lang).label+' = '+f(command.value);}catch(e){$('#form-error').textContent=e.message;return;}}
  const req=snapshot(question,inputMode),serial=++turn;$('#ask').disabled=true;$('#ask').textContent=tr('Thinking…','Einen Moment…');$('#form-error').textContent='';
  let answer;
  try{const r=await fetch('/api/lesson',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(req),signal:AbortSignal.timeout(21000)});const j=await r.json();if(serial!==turn)return;if(!r.ok){$('#form-error').textContent=j.error;return;}answer=validateLesson(j,req);}catch{if(serial!==turn)return;answer=preparedLesson(req,'client-fallback');$('#form-error').textContent=tr('Connection unavailable; using prepared content.','Verbindung nicht verfügbar; vorbereitete Erklärung.');}finally{if(serial===turn){$('#ask').disabled=false;$('#ask').textContent=tr('Send','Senden');}}
  if(serial!==turn||!answer)return;showAnswer(answer,req);answer.sceneActions.forEach(a=>focus(a.target));if($('#spoken-reply').checked&&!$('#video-dialog').open)voice.speak(req,answer.paragraphIds);
}
async function initScene(){const canvas=$('#venue');try{const {createVenue}=await import('./scene.js');if(!canvas.isConnected)return;const v=await createVenue(canvas,focus,()=>{},'concert');if(!canvas.isConnected){v.dispose();return;}world=v;sceneAvailable=true;world.update(scenario,calculateScenario(id,scenario));world.pause(paused);world.reduced(reduced);canvas.dataset.loaded='true';$('#scene-loading').hidden=true;updateView();}catch(e){console.warn('Scene unavailable:',String(e));if(canvas.isConnected){$('#scene-loading').textContent=tr('The scene could not load. Your dashboard and numbers still work.','Die Szene konnte nicht geladen werden. Dashboard und Zahlen funktionieren weiterhin.');$('#retry-scene').hidden=false;}}}
async function openVideo(){voice.cancel();$('#video-dialog').showModal();try{const r=await fetch(`/media/${lesson().scene}-${lang}.txt`);$('#video-transcript').textContent=r.ok?await r.text():tr('Transcript unavailable.','Transkript nicht verfügbar.');await $('#explainer').play();}catch{$('#video-transcript').textContent=tr('Press Play to start. If playback fails, read the transcript or explore the live lesson.','Zum Starten auf Abspielen drücken. Bei Problemen kannst du den Text lesen oder die Live-Lektion erkunden.');}}
addEventListener('popstate',()=>{const path=normalizeId(location.pathname.split('/')[2]||'concert');lang=new URL(location.href).searchParams.get('lang')==='de'?'de':'en';switchLesson(LESSONS[path]?path:'concert-economics',false);});
try{const stored=JSON.parse(localStorage.getItem('concert-mix')||'null');if(stored?.scenario){saved=validateScenario(id,stored.scenario);savedPlan=stored.saveVersion===2?stored.planning:null;savedVariables=Array.isArray(stored.visibleVariables)?stored.visibleVariables.filter(k=>optionalKeys.includes(k)):optionalKeys.filter(k=>saved[k]!==defaults(id)[k]);}}catch{}
if(location.pathname==='/methodology'){$('#app').innerHTML=`<main class="methodology"><a href="/lessons/${id}?lang=${lang}">${tr('Back to lesson','Zur Lektion')}</a><h1>${tr('Behind the model','Hinter dem Modell')}</h1><div>${Object.values(approvedParagraphs(snapshot('overview'))).map(p=>`<p>${p}</p>`).join('')}</div><pre>${'D = floor(M × (1 + promotionBoost / 100) × (p / 20)^(-e))\nA = min(capacity, manual ? requestedAttendance : D)\nCost = production + venueRate × capacity + perGuest × A + promotionBudget\nRevenue = p × A + sponsorship\nProfit = revenue − cost\nROI = costs > 0 ? 100 × profit / costs : undefined\nUSD · money is calculated in integer cents'}</pre></main>`;}else render();
// Deterministic capture hooks for preset explainer production; never execute model code.
window.lessonCapture={set:(values)=>change(values,true),focus,seek:t=>world?.seek(t),portrait:()=>world?.portrait(),state:()=>({id,scenario:{...scenario},result:calculateScenario(id,scenario)}),switch:id=>switchLesson(id,false)};
