import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/700.css';
import '@fontsource/manrope/500.css';
import '@fontsource/manrope/800.css';
import './style.css';
import {LESSONS,defaults,normalizeId,validateScenario,calculateScenario} from '../shared/registry.js';
import {preparedLesson,approvedParagraphs,validateLesson} from '../shared/lesson.js';
import {parseCommand} from '../shared/commands.js';
import {voiceController} from './voice.js';
import './experience.css';
import {fieldContent,workedExample,setupText,changeExplanation,zoneContent,deriveSceneState} from '../shared/teaching.js';
import {renderIllustration} from './illustration.js';
import './teaching.css';

const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const url=new URL(location.href);let lang=url.searchParams.get('lang')==='de'?'de':'en';
let id=normalizeId(location.pathname.split('/')[2]||url.searchParams.get('lesson')||'concert');if(!LESSONS[id])id='concert-economics';
let scenario=defaults(id),previous=null,saved=null,revision=0,turn=0,world,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,paused=reduced,flat=false,lastAnswer,lastRequest,selectedZone=null,sceneAvailable=false,transcriptMode='text',changedFields=[],undoState=null,dragStart=null;
const sessionId=crypto.randomUUID();const tr=(en,de)=>lang==='de'?de:en;const f=n=>n===null?tr('N/A','n. a.'):new Intl.NumberFormat(lang==='de'?'de-DE':'en-US',{maximumFractionDigits:2}).format(n);
const lesson=()=>LESSONS[id];const snapshot=(question,inputMode='text')=>({requestId:crypto.randomUUID(),sessionId,topicId:id,language:lang,question,scenario:{...scenario},previousScenario:previous?{...previous}:null,scenarioRevision:revision,inputMode});
const voice=voiceController({language:()=>lang,onTranscript:text=>{if($('#question')){$('#question').value=text;$('#transcript').textContent=tr('Recognized speech — correct the text, then send.','Erkannter Text — bitte prüfen, dann senden.');transcriptMode='voice';$('#question').focus();}},onStatus:text=>{if($('#voice-status'))$('#voice-status').textContent=text;},onRecording:yes=>{if($('#mic')){$('#mic').disabled=yes;$('#record-stop').hidden=!yes;$('#record-cancel').hidden=!yes;$('#mic').classList.toggle('recording',yes);}}});

function invalidate(){turn++;revision++;lastAnswer=null;lastRequest=null;voice.cancel();if($('#ask')){$('#ask').disabled=false;$('#ask').textContent=tr('Send','Senden');}if($('#replay'))$('#replay').disabled=true;}
function field(row){const key=row[0],meta=fieldContent(id,key,lang),value=scenario[key];return `<label class="field" for="field-${key}" data-field="${key}"><span>${meta.label}</span><div class="field-value"><input id="field-${key}" data-input="${key}" type="number" min="${meta.min}" max="${meta.max}" step="${meta.step}" value="${value}" inputmode="decimal" aria-describedby="help-${key}"/><small>${meta.unit}</small></div><small class="field-help" id="help-${key}">${meta.help}</small><small class="worked-example" data-example="${key}"></small>${meta.group==='primary'?`<input aria-label="${meta.label} ${tr('slider','Regler')}" data-range="${key}" type="range" min="${meta.min}" max="${key==='capacity'?Math.max(2000,value):key==='ticketPrice'?Math.max(100,value):meta.max}" step="${meta.step}" value="${value}"/>`:''}${key==='elasticity'?`<div class="sensitivity">${[[.5,tr('Low','Niedrig')],[1,tr('Medium','Mittel')],[2,tr('High','Hoch')]].map(([n,t])=>`<button type="button" data-sensitivity="${n}">${t} · ${f(n)}</button>`).join('')}</div>`:''}</label>`;}
function groupedFields(){const names={audience:tr('Change audience assumptions','Nachfrageannahmen ändern'),costs:tr('Change costs and assumptions','Kosten und Annahmen ändern')};return Object.entries(names).map(([group,title])=>{const rows=lesson().fields.filter(r=>fieldContent(id,r[0],lang).group===group);return rows.length?`<details class="advanced" data-group="${group}"><summary>${title}</summary>${rows.map(field).join('')}</details>`:'';}).join('');}
function render(push=false){
  flat=false;world?.dispose();world=null;sceneAvailable=false;voice.cancel();turn++;document.documentElement.lang=lang;
  const l=lesson();if(push)history.pushState({},'',`/lessons/${id}?lang=${lang}`);
  document.title=l.title[lang]+' — The Economics of Everything';
  $('#app').innerHTML=`<header class="site-header"><a class="brand" href="/"><span class="brand-mark">e<span>•</span></span><span>The Economics<br>of Everything</span></a><span class="header-lab">${tr('SMALL WORLDS. REAL INSIGHTS.','KLEINE WELTEN. ECHTE ERKENNTNISSE.')}</span><select id="language" aria-label="Language / Sprache"><option value="en" ${lang==='en'?'selected':''}>English</option><option value="de" ${lang==='de'?'selected':''}>Deutsch</option></select></header>
  <main class="experience"><div class="eyebrow concert-heading">01 / ${tr('The concert','Das Konzert')}</div>
  <div class="compact-title"><div><h1>${l.question[lang]}</h1><p id="setup">${setupText(id,scenario,lang)}</p><small class="money-note">${tr('Fictional example · amounts in currency units (CU)','Erfundenes Beispiel · Beträge in Geldeinheiten (GE)')}</small></div><button id="watch" class="primary">▶ ${tr('Watch the short story','Die Kurzgeschichte ansehen')}</button></div>
  <div class="experience-grid"><section class="world-panel"><div class="world-top"><span class="eyebrow">${tr('YOUR LIVE WORLD','DEINE LIVE-WELT')}</span><div class="world-tools"><button id="pause" aria-pressed="${paused}">${paused?tr('Play motion','Bewegung starten'):tr('Pause motion','Bewegung pausieren')}</button><button id="reset-camera">${tr('Reset view','Ansicht zurücksetzen')}</button><button id="toggle-view">${flat?tr('Spatial view','Räumliche Ansicht'):tr('Lightweight view','Leichte Ansicht')}</button></div></div><div class="canvas-wrap"><canvas id="venue" aria-label="${tr('Drag to orbit. Select a labeled zone below to explore.','Ziehen zum Drehen. Wähle unten einen Bereich.') }" tabindex="0"></canvas><div id="scene-loading" role="status">${tr('Opening your world…','Deine Welt wird geöffnet…')}</div><div id="flat-view" hidden></div><div class="scene-badge" id="scene-badge"></div></div><div class="world-bottom"><span id="view-instruction">${tr('Select a scene area to explore','Wähle einen Szenenbereich')}</span><span>${tr('Figures represent groups, not individual headcounts.','Figuren stehen für Gruppen, nicht Einzelpersonen.')}</span></div>
  <div class="hotspots">${l.zones.map((z,i)=>`<button data-zone="${z}" aria-pressed="false">${String(i+1).padStart(2,'0')} ${l.zoneLabels[lang][i]}</button>`).join('')}</div><div class="context-card" aria-live="polite"><div><span class="eyebrow" id="context-title">${tr('EXPLORE A PART OF THE WORLD','ERKUNDE EINEN BEREICH')}</span><p id="context-text">${tr('Select a labeled zone above. The camera will move closer and its explanation will appear here.','Wähle oben einen Bereich. Die Kamera fährt näher heran und hier erscheint die Erklärung.')}</p></div><button id="experiment" hidden></button><button id="context-ask">${tr('Ask about this','Dazu eine Frage stellen')}</button></div>
  <div class="quick-results" aria-live="polite" id="quick-results"></div></section>
  <aside><details class="control-tray" open><summary>${tr('Try a change','Probiere eine Änderung')} <span>＋</span></summary><p class="control-hint" id="primary-hint"></p><div class="fields">${l.fields.filter(r=>fieldContent(id,r[0],lang).group==='primary').map(field).join('')}</div></details><div id="optional-fields">${groupedFields()}<details class="advanced"><summary>${tr('Try a named example','Ein Beispiel auswählen')}</summary><div class="preset-row">${l.presets.map((p,i)=>`<button data-preset="${i}">${p[lang]}</button>`).join('')}</div><p class="control-hint">${tr('Each preset lists every setting it changes below.','Jede Voreinstellung zeigt unten alle geänderten Werte.')}</p></details></div>
  ${''}
  <div class="scenario-actions"><button id="reset-scenario">${tr('Reset lesson settings','Lektion zurücksetzen')}</button><button id="save-scenario">${tr('Save this version','Diese Version speichern')}</button></div><section class="change-card"><h2>${tr('What changed?','Was hat sich geändert?')}</h2><p id="causal-change" aria-live="polite"></p><p id="change-notice" role="status"></p><button id="undo" disabled>${tr('Undo last change','Letzte Änderung rückgängig')}</button></section><details class="result-card"><summary>${tr('More details · costs and results','Mehr Details · Kosten und Ergebnisse')}</summary><div class="eyebrow">${tr('THE NUMBERS','DIE ZAHLEN')}</div><div id="breakdown"></div><div id="metrics"></div><small>${tr('Illustrative currency units. No real-world forecast.','Erfundene Geldeinheiten. Keine echte Prognose.')}</small></details></aside></div>
  <section id="comparison" class="comparison" hidden></section>
  <section class="tutor-section"><div><div class="eyebrow">${tr('ASK. LISTEN. TRY SOMETHING.','FRAGEN. ZUHÖREN. AUSPROBIEREN.')}</div><h2>${tr('Ask about this scenario.','Frage zu diesem Szenario.')}</h2><p>${tr('Type a question or speak. Your answer uses the lesson and numbers you see right now.','Tippe oder sprich. Die Antwort bezieht sich auf die aktuelle Lektion und deine Zahlen.')}</p><div class="question-chips">${l.questions[lang].map((q,i)=>`<button data-question="${i}">${q}</button>`).join('')}</div></div><div class="tutor-card"><div class="tutor-heading"><span class="tutor-avatar">e•</span><span id="delivery">${tr('Prepared explanation','Vorbereitete Erklärung')}</span></div><p id="explanation" aria-live="polite"></p><p id="transcript"></p><form id="ask-form"><label for="question">${tr('Your question','Deine Frage')}</label><textarea id="question" maxlength="600" rows="2" placeholder="${l.questions[lang][0]}" required></textarea><div class="form-bottom"><button type="button" id="mic" aria-label="${tr('Speak a question','Frage sprechen')}" title="${tr('Speak a question','Frage sprechen')}"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/></svg></button><button type="button" id="record-stop" hidden>${tr('Stop recording','Aufnahme stoppen')}</button><button type="button" id="record-cancel" hidden>${tr('Cancel','Abbrechen')}</button><button id="ask" type="submit">${tr('Send','Senden')}</button></div></form><div class="audio-tools"><label><input id="spoken-reply" type="checkbox">${tr('Speak replies','Antworten vorlesen')}</label><button id="replay" disabled>${tr('Replay answer','Antwort abspielen')}</button><button id="mute">${tr('Stop audio','Audio stoppen')}</button>${url.searchParams.has('review')?`<button id="voice-sample">${tr('Audition voice','Stimme anhören')}</button>`:''}</div><p id="voice-status" role="status"></p><p id="form-error" role="alert"></p><small>${tr('Voice is AI-generated. Recording starts only when you choose it; up to 30 seconds. Questions go to the lesson service. Please omit personal information.','Die Stimme ist KI-generiert. Aufnahme nur nach deiner Auswahl, bis zu 30 Sekunden. Fragen gehen an den Lerndienst. Bitte keine persönlichen Daten.')}</small></div></section>
  <details class="assumptions"><summary>${tr('How the model works','So funktioniert das Modell')} <span>＋</span></summary><div id="assumptions"></div><a href="/methodology?lesson=${id}&lang=${lang}">${tr('Read formulas and assumptions','Formeln und Annahmen lesen')}</a></details>
  <dialog id="video-dialog"><div class="video-heading"><h2>${l.title[lang]} · ${tr('Preset story','Vorgegebenes Beispiel')}</h2><button id="close-video">${tr('Close','Schließen')}</button></div><p>${tr('This video uses a fixed example. Live controls do not change recorded numbers.','Das Video zeigt ein festes Beispiel. Live-Regler ändern die aufgenommenen Zahlen nicht.')}</p><video id="explainer" controls playsinline preload="metadata" poster="/media/${l.scene}-${lang}-poster.jpg"><source src="/media/${l.scene}-${lang}.mp4" type="video/mp4"><track kind="captions" src="/media/${l.scene}-${lang}.vtt" srclang="${lang}" label="${lang==='en'?'English':'Deutsch'}" default></video><details><summary>${tr('Read transcript','Transkript lesen')}</summary><div id="video-transcript"></div></details></dialog>
  </main><footer><span>${tr('Small worlds. Useful ideas.','Kleine Welten. Nützliche Ideen.')}</span><a href="/">${tr('The concert','Das Konzert')}</a><span>n8n · Blender · Babylon.js</span></footer>`;
  $('#language').onchange=e=>{lang=e.target.value;invalidate();render(true);};
  all('[data-lesson]').forEach(el=>el.onclick=e=>{e.preventDefault();switchLesson(el.dataset.lesson);});
  all('[data-input]').forEach(el=>el.onchange=()=>change({[el.dataset.input]:Number(el.value)}));
  all('[data-range]').forEach(el=>{el.onpointerdown=()=>{dragStart={...scenario};};el.oninput=()=>change({[el.dataset.range]:Number(el.value)});el.onchange=()=>{dragStart=null;};});
  all('[data-preset]').forEach(el=>el.onclick=()=>{const p=l.presets[Number(el.dataset.preset)];change(p.values);$('#change-notice').textContent=tr('Changed: ','Geändert: ')+Object.entries(p.values).map(([k,v])=>fieldContent(id,k,lang).label+' = '+f(v)+' '+fieldContent(id,k,lang).unit).join('; ');});
  all('[data-zone]').forEach(el=>el.onclick=()=>focus(el.dataset.zone));
  $('#pause').onclick=()=>{paused=!paused;world?.pause(paused);$('#pause').textContent=paused?tr('Play motion','Bewegung starten'):tr('Pause motion','Bewegung pausieren');$('#pause').setAttribute('aria-pressed',paused);drawFlat(calculateScenario(id,scenario));};
  const reducedControl=document.createElement('label');reducedControl.className='reduced-control';reducedControl.innerHTML=`<input type="checkbox" id="reduced-motion" ${reduced?'checked':''}>${tr('Reduced motion','Weniger Bewegung')}`;$('.world-bottom').append(reducedControl);document.body.classList.toggle('reduce-motion',reduced);$('#reduced-motion').onchange=e=>{reduced=e.target.checked;world?.reduced(reduced);if(reduced&&!paused)$('#pause').click();document.body.classList.toggle('reduce-motion',reduced);};
  $('#reset-camera').onclick=()=>{world?.reset();selectedZone=null;all('[data-zone]').forEach(b=>b.setAttribute('aria-pressed','false'));$('#experiment').hidden=true;$('#context-title').textContent=tr('Explore the scene','Erkunde die Szene');drawFlat(calculateScenario(id,scenario));$('#context-text').textContent=tr('Full world view restored. Select a zone to explore.','Gesamtansicht wiederhergestellt. Wähle einen Bereich.');};
  all('[data-sensitivity]').forEach(b=>b.onclick=()=>change({elasticity:Number(b.dataset.sensitivity)}));
  $('#undo').onclick=()=>{if(undoState){const values=undoState;undoState=null;change(values,true);undoState=null;$('#undo').disabled=true;}};
  $('#experiment').onclick=()=>{const z=zoneContent(id,selectedZone,scenario,calculateScenario(id,scenario),lang);change(z.values);};
  $('#flat-view').onclick=e=>{const area=e.target.closest('[data-illustration-zone]');if(area)focus(area.dataset.illustrationZone);};
  $('#toggle-view').onclick=()=>{flat=!flat;updateView();};
  $('#reset-scenario').onclick=()=>{saved=null;$('#save-scenario').textContent=tr('Save this version','Diese Version speichern');change(defaults(id));world?.reset();};
  $('#save-scenario').onclick=()=>{saved={...scenario};updateComparison();$('#save-scenario').textContent=tr('Replace saved version','Gespeicherte Version ersetzen');};
  $('#ask-form').onsubmit=e=>{e.preventDefault();ask($('#question').value,transcriptMode);transcriptMode='text';};
  all('[data-question]').forEach(el=>el.onclick=()=>{const q=l.questions[lang][Number(el.dataset.question)];$('#question').value=q;ask(q);});
  $('#context-ask').onclick=()=>{$('#question').value=tr('Explain ','Erkläre ')+(selectedZone?l.zoneLabels[lang][l.zones.indexOf(selectedZone)]:l.title[lang]);$('#question').focus();$('#ask-form').scrollIntoView({behavior:'smooth',block:'center'});};
  $('#mic').onclick=()=>voice.start();$('#record-stop').onclick=()=>voice.stop();$('#record-cancel').onclick=()=>{voice.cancel();$('#voice-status').textContent=tr('Recording canceled. Microphone released.','Aufnahme abgebrochen. Mikrofon freigegeben.');};
  $('#mute').onclick=()=>{voice.stopAudio();$('#spoken-reply').checked=false;$('#voice-status').textContent=tr('Audio stopped.','Audio gestoppt.');};
  $('#replay').onclick=()=>{if(lastAnswer&&lastRequest)voice.speak(lastRequest,lastAnswer.paragraphIds);};
  if($('#voice-sample'))$('#voice-sample').onclick=()=>{voice.cancel();const r=snapshot('overview');voice.speak(r,['overview']);};
  $('#watch').onclick=()=>openVideo();$('#close-video').onclick=()=>{$('#explainer').pause();$('#video-dialog').close();};$('#explainer').onplay=()=>voice.cancel();
  $('#video-dialog').addEventListener('cancel',()=>$('#explainer').pause());
  arrangeTeachingLayout();update();initScene();
}
function arrangeTeachingLayout(){
 const grid=$('.experience-grid'),aside=grid.querySelector('aside');
 const explore=document.createElement('details');explore.className='explore-panel';explore.innerHTML=`<summary>${tr('Explore the scene','Erkunde die Szene')}</summary>`;explore.append($('.hotspots'),$('.context-card'));grid.after(explore);
 const optional=document.createElement('details');optional.className='more-settings';optional.innerHTML=`<summary>${tr('More decisions and assumptions','Weitere Entscheidungen und Annahmen')}</summary>`;optional.append($('#optional-fields'));explore.after(optional);
 grid.append($('.quick-results'),$('.change-card'));aside.className='decision-panel';
 const details=$('.result-card');optional.after(details);grid.append($('.scenario-actions'));
 $('#world-hint')?.remove();const hint=document.createElement('p');hint.id='world-hint';hint.textContent=tr('Pause motion freezes the illustration only. Reset view changes only the camera.','Bewegung pausieren hält nur die Darstellung an. Ansicht zurücksetzen ändert nur die Kamera.');$('.world-bottom').append(hint);
}
function metricLabel(key,en,de,c){
 const labels={attendance:tr('Expected people','Erwartete Personen'),potentialDemand:tr('People who would buy at this price','Kaufbereite zu diesem Preis'),occupancy:tr('How full the venue is · %','Auslastung · %'),unmetDemand:tr('Buyers who cannot fit','Kaufbereite ohne Platz'),revenue:tr('Total income · CU','Einnahmen · GE'),totalCost:tr('Total event costs · CU','Gesamte Veranstaltungskosten · GE'),returnOnCost:tr('Profit ÷ costs · % (N/A if costs are zero)','Gewinn ÷ Kosten · % (n. a. bei Kosten null)'),profit:c.profit<0?tr('Loss / shortfall · CU','Verlust / Fehlbetrag · GE'):tr('Money left after costs · CU','Geld nach Kosten · GE')};return labels[key]||tr(en,de);
}
function updateTeaching(c){
 const s=scenario,l=lesson(),cu=tr('CU','GE');$('#setup').textContent=setupText(id,s,lang);$('#causal-change').textContent=changeExplanation(id,s,previous,lang);$('#undo').disabled=!undoState;
 all('[data-example]').forEach(e=>e.textContent=workedExample(id,e.dataset.example,s,c,lang));
 all('[data-sensitivity]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.sensitivity)===s.elasticity));
 $('#primary-hint').textContent=tr(`Starting assumption: ${f(s.demand)} buyers at 20 CU. More venue space does not create buyers.`,`Annahme: ${f(s.demand)} Kaufbereite bei 20 GE. Mehr Platz erzeugt keine Käufer.`);
 let rows=[[tr('Stage, DJ and sound','Bühne, DJ und Ton'),s.productionBudget],[tr('Venue hire','Saalmiete'),c.venueCost],[tr('Guest supplies and services','Material und Leistungen pro Gast'),c.variableCost]];
 $('#breakdown').innerHTML=`<h3>${tr('Where the money goes','Wohin das Geld fließt')}</h3>${rows.map(([k,v])=>`<div class="cost-line"><span>${k}</span><b>${f(v)} ${cu}</b></div>`).join('')}<p>${tr(`${f(c.attendance)} of ${f(s.capacity)} places filled (${f(c.occupancy)}%). Venue hire is paid for all places.`,`${f(c.attendance)} von ${f(s.capacity)} Plätzen belegt (${f(c.occupancy)}%). Miete fällt für alle Plätze an.`)}</p>`;
}
function switchLesson(next,push=true){dragStart=null;undoState=null;invalidate();id=next;scenario=defaults(id);previous=null;saved=null;selectedZone=null;render(push);}
function change(values,restore=false){try{let next=validateScenario(id,{...scenario,...values});changedFields=Object.keys(next).filter(k=>scenario[k]!==next[k]);if(!changedFields.length){updateComparison();return;};undoState={...(dragStart||scenario)};previous={...(dragStart||scenario)};scenario=next;invalidate();update();$('#change-notice').textContent='';}catch(e){$('#change-notice').textContent=lang==='de'?'Bitte gültige Zahlen innerhalb der angegebenen Grenzen eingeben. Die bisherigen Einstellungen bleiben erhalten.':e.message;syncInputs();}}
function syncInputs(){all('[data-input]').forEach(el=>el.value=scenario[el.dataset.input]);all('[data-range]').forEach(el=>{const v=scenario[el.dataset.range];if(v>Number(el.max))el.max=v;el.value=v;});}
function update(){
  const l=lesson(),c=calculateScenario(id,scenario);syncInputs();world?.update(scenario,c,deriveSceneState(id,scenario,c,selectedZone));
  $('#metrics').innerHTML=l.metrics.map(([key,en,de])=>`<div class="metric ${key==='profit'?'main-metric '+(c.profit<0?'negative':''):''}"><span>${metricLabel(key,en,de,c)}</span><strong data-metric="${key}">${f(c[key])}</strong></div>`).join('');
  const quick=[['attendance',tr('Expected people','Erwartete Personen')],['revenue',tr('Total income · CU','Einnahmen · GE')],['totalCost',tr('Total costs · CU','Gesamtkosten · GE')],['profit',c.profit<0?tr('Loss · CU','Verlust · GE'):tr('Profit · CU','Gewinn · GE')]];
  $('#quick-results').innerHTML=quick.map(([k,label])=>`<div><span>${label}</span><strong>${f(c[k])}</strong></div>`).join('');
  updateTeaching(c);
  $('#scene-badge').textContent=`${f(c.occupancy)}% ${tr('occupied','belegt')} · ${f(scenario.capacity)} ${tr('places','Plätze')}`;
  drawFlat(c);const req=snapshot('overview');showAnswer(preparedLesson(req),req);$('#assumptions').replaceChildren(...Object.values(approvedParagraphs(req)).slice(0,6).map(text=>{const p=document.createElement('p');p.textContent=text;return p;}));
  if(selectedZone)focus(selectedZone,false);updateComparison();
}
function drawFlat(c){$('#flat-view').innerHTML=renderIllustration(deriveSceneState(id,scenario,c,selectedZone),scenario,c,lang);$('#flat-view').classList.toggle('motion-paused',paused||reduced);}
function updateView(){$('#venue').hidden=flat;$('#flat-view').hidden=!flat;$('#toggle-view').hidden=!sceneAvailable;$('#reset-camera').hidden=flat;$('#toggle-view').textContent=flat?tr('Spatial view','Räumliche Ansicht'):tr('Lightweight view','Leichte Ansicht');$('#venue').setAttribute('aria-label',tr('Drag to look around. Select an area below for an explanation.','Ziehen zum Umsehen. Wähle unten einen Bereich für eine Erklärung.'));$('#view-instruction').textContent=flat?tr('Select an area below to explore','Wähle unten einen Bereich'):tr('Drag to look around · select an area below','Ziehen zum Umsehen · unten Bereich wählen');world?.pause(paused||flat);}
function focus(zone,move=true){if(move&&!document.body.classList.contains('capture-mode'))$('.explore-panel').open=true;selectedZone=zone;const l=lesson(),index=l.zones.indexOf(zone);if(index<0)return;all('[data-zone]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.zone===zone));if(move)world?.focus(zone);const c=calculateScenario(id,scenario),z=zoneContent(id,zone,scenario,c,lang);$('#context-title').textContent=tr('Looking at: ','Im Blick: ')+l.zoneLabels[lang][index];$('#context-text').textContent=z.status+' '+z.meaning;$('#experiment').hidden=false;$('#experiment').textContent=tr('Try: ','Ausprobieren: ')+Object.entries(z.values).map(([k,v])=>fieldContent(id,k,lang).label+' → '+f(v)+' '+fieldContent(id,k,lang).unit).join('; ')+('');drawFlat(c);}
function updateComparison(){const el=$('#comparison');if(!saved){el.hidden=true;return;}el.hidden=false;const a=calculateScenario(id,saved),b=calculateScenario(id,scenario);el.innerHTML=`<h2>${tr('Compare with saved version','Mit gespeicherter Version vergleichen')}</h2><p>${tr('Change any input to compare against A. Saved only for this open lesson.','Ändere eine Eingabe zum Vergleich mit A. Nur in dieser geöffneten Lektion gespeichert.')}</p><div class="compare-scroll"><table><thead><tr><th>${tr('Measure','Kennzahl')}</th><th>${tr('Saved','Gespeichert')}</th><th>${tr('Current','Aktuell')}</th><th>${tr('Difference','Differenz')}</th></tr></thead><tbody>${lesson().metrics.map(([k,en,de])=>`<tr><td>${tr(en,de)}</td><td>${f(a[k])}</td><td>${f(b[k])}</td><td>${a[k]===null||b[k]===null?'—':f(b[k]-a[k])}</td></tr>`).join('')}</tbody></table></div>`;}
function showAnswer(answer,request){lastAnswer=answer;lastRequest=request;$('#explanation').textContent=answer.explanation;$('#delivery').textContent=answer.fallbackUsed?tr('Prepared explanation','Vorbereitete Erklärung'):tr('AI-selected explanation · checked numbers','KI-Auswahl · geprüfte Zahlen');$('#replay').disabled=false;}
async function ask(question,inputMode='text'){
  if(!question.trim())return;voice.cancel();document.querySelectorAll('video').forEach(v=>v.pause());const command=parseCommand(question,id,lang);
  if(command){if(command.clarification){$('#form-error').textContent=tr('What exact number should I use? Say or type it with the setting.','Welche genaue Zahl soll ich verwenden? Nenne sie mit der Einstellung.');return;}try{validateScenario(id,{...scenario,[command.field]:command.value});change({[command.field]:command.value});$('#transcript').textContent=tr('Applied (Undo is available): ','Angewendet (rückgängig möglich): ')+fieldContent(id,command.field,lang).label+' = '+f(command.value);}catch(e){$('#form-error').textContent=e.message;return;}}
  const req=snapshot(question,inputMode),serial=++turn;$('#ask').disabled=true;$('#ask').textContent=tr('Thinking…','Einen Moment…');$('#form-error').textContent='';
  let answer;
  try{const r=await fetch('/api/lesson',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(req),signal:AbortSignal.timeout(21000)});const j=await r.json();if(serial!==turn)return;if(!r.ok){$('#form-error').textContent=j.error;return;}answer=validateLesson(j,req);}catch{if(serial!==turn)return;answer=preparedLesson(req,'client-fallback');$('#form-error').textContent=tr('Connection unavailable; using prepared content.','Verbindung nicht verfügbar; vorbereitete Erklärung.');}finally{if(serial===turn){$('#ask').disabled=false;$('#ask').textContent=tr('Send','Senden');}}
  if(serial!==turn||!answer)return;showAnswer(answer,req);answer.sceneActions.forEach(a=>focus(a.target));if($('#spoken-reply').checked&&!$('#video-dialog').open)voice.speak(req,answer.paragraphIds);
}
async function initScene(){const canvas=$('#venue');try{const {createVenue}=await import('./scene.js');if(!canvas.isConnected)return;const v=await createVenue(canvas,focus,()=>{},lesson().scene);if(!canvas.isConnected){v.dispose();return;}world=v;sceneAvailable=true;world.update(scenario,calculateScenario(id,scenario));world.pause(paused||flat);world.reduced(reduced);canvas.dataset.loaded='true';$('#scene-loading').hidden=true;updateView();}catch(e){console.warn('Scene fallback:',String(e));if(canvas.isConnected){$('#scene-loading').hidden=true;flat=true;updateView();$('#context-text').textContent=tr('Lightweight view is ready. Select an area to explore; all decisions and results work here.','Die leichte Ansicht ist bereit. Wähle einen Bereich; alle Entscheidungen und Ergebnisse funktionieren hier.');}}}
async function openVideo(){voice.cancel();$('#video-dialog').showModal();try{const r=await fetch(`/media/${lesson().scene}-${lang}.txt`);$('#video-transcript').textContent=r.ok?await r.text():tr('Transcript unavailable.','Transkript nicht verfügbar.');await $('#explainer').play();}catch{$('#video-transcript').textContent=tr('Press Play to start. If playback fails, read the transcript or explore the live lesson.','Zum Starten auf Abspielen drücken. Bei Problemen kannst du den Text lesen oder die Live-Lektion erkunden.');}}
addEventListener('popstate',()=>{const path=normalizeId(location.pathname.split('/')[2]||'concert');lang=new URL(location.href).searchParams.get('lang')==='de'?'de':'en';switchLesson(LESSONS[path]?path:'concert-economics',false);});
if(location.pathname==='/methodology'){$('#app').innerHTML=`<main class="methodology"><a href="/lessons/${id}?lang=${lang}">${tr('Back to lesson','Zur Lektion')}</a><h1>${tr('Behind the model','Hinter dem Modell')}</h1><div>${Object.values(approvedParagraphs(snapshot('overview'))).map(p=>`<p>${p}</p>`).join('')}</div><pre>${'D = floor(M × (p / 20)^(-e))\nA = min(capacity, D)\nCost = production + venueRate × capacity + perGuest × A\nRevenue = p × A\nProfit = revenue − cost'}</pre></main>`;}else render();
// Deterministic capture hooks for preset explainer production; never execute model code.
window.lessonCapture={set:(values)=>change(values,true),focus,seek:t=>world?.seek(t),portrait:()=>world?.portrait(),state:()=>({id,scenario:{...scenario},result:calculateScenario(id,scenario)}),switch:id=>switchLesson(id,false)};
